- source/distributing.rst
- source/installing.rst
many edits to the packaging tutorial, with the 2 main changes being:
1. redo the "Layout" section into a section on the "Initial Files".
2. restructured the info on setup args into literal sections by arg name
built html:  https://packaging.python.org/en/setup_args/distributing.html
> restructure the "Layout" section and sections related to setup() args

- source/additional.rst
- source/distributing.rst
- source/glossary.rst
- source/installing.rst
- source/projects.rst
- source/quickstart.rst
our intro sections aren't "tutorials" right now, so let's not set up a false expectation for the reader.
tutorials involve literal tasks that the reader is guided though with clear results and checks along the way.
whether they should be tutorials or not is another matter, but they're not currently.  I don't have any plans to make them true tutorials.   I can imagine having actual tutorials in the advanced section for certain topics possibly.
In the title, I simply remove the word "Tutorial", but in the text, I replaced "tutorial" with "section".
this does not break any external inbound links.
> don't call our intro sections "tutorials", because they're not

- source/deployment.rst
I just learned about [pynsist](https://github.com/takluyver/pynsist), and saw that it is still missing from this guide. Maybe wait for @takluyver to look over the draft before merging.
> Add summary of pynsist in OS packaging and installers section

- source/distributing.rst
A few of the code blocks had extraneous spacing. 
Also, it might be worth adding trailing commas to the code snippets to match https://github.com/pypa/sampleproject/blob/master/setup.py — would make it easier to copy/paste. Let me know if you'd like for me to add that into this PR.
> Consistent style in code blocks

- source/single_source_version.rst
Should be less confusing for newbies (as the assert is not actually required).
(someone asked this on irc: `17:54 <karlpinc> ionelmc: Good point.  Regards choice 3, the exec choice, I don't understand why the example code includes an assert statement.`)
> Replace asserts with comments in example code

- source/code/appveyor.yml
The labels of the pre-installed versions are currently wrong for 2.7
and 3.4, as Appveyor has updated the version, and install.ps1 does not
override the pre-installed version.
> Use A.B.x labels for pre-installed versions

- source/code/appveyor.yml
Packagers may be needing to do a Python 2.6 Win32 release.
> Add 2.6.6 to the Appveyor build matrix

- source/pip_easy_install.rst
In writing a project which includes console-scripts, I wanted to install the package but not have it generate the scripts. In reading the help for pip, I don't see any option to exclude the script installation. I believe that reveals another difference between easy_install and pip.
> easy_install has a -x option to exclude scripts from the install

- source/current.rst
This was a recommendation for speeding up subsequent installations, but `pip` now automatically builds wheels in a cache since 7.0, so there's questionable utility in keeping it here.
> Remove wheel reference in tool recommendations

- source/distributing.rst
- source/installing.rst
- The installation tutorial now covers installing wheel, since it's critical for wheel caching
- Mention that Python 2.7.9 has pip bootstrapping
- replace the old "pip wheel" caching instructions with general info about wheels and that pip has a wheel cache
- add a warning about using `get-pip.py` in managed pythons
> Installation Tutorial updates

- source/install_requirements_linux.rst
The IUS project has launched a [new website](https://ius.io).  Here are some URL corrections.
> update IUS links

- source/projects.rst
The user-contributed repository for *conda* packages formerly named binstar.org is now called anaconda.org, and the domain http://binstar.org redirects to http://anaconda.org.
> Replace "binstar.org" with "anaconda.org"

- source/conf.py
A tiny change to add the current year to the copyright statement, like that of other python.org pages.
> Update copyright year

- source/current.rst
- source/distributing.rst
- source/glossary.rst
- source/installing.rst
- source/pip_easy_install.rst
- source/wheel_egg.rst
During the build process, several warnings appear about undefined labels linking to PEPs (via the PyPA intersphinx mapping). For example:
```
/Users/ddbeck/projects/python-packaging-user-guide/source/wheel_egg.rst:37: WARNING: undefined label: pypa:pep425s (if the link has no caption the label must precede a section header)
```
This pull request replaces the broken PyPA labels and hardcoded PEP URLs with `:pep:` inline text roles. After these changes, the build completes without any warnings or errors (at least for me).
> Fix undefined label build warnings

- source/contribute.rst
- source/index.rst
Here's the inaugural pull request in [the process of writing new tutorials and other improvements](https://mail.python.org/pipermail/distutils-sig/2015-November/027776.html). This adds a brief call to contribute and the start of a style guide. Bear in mind that this is going to be something of a living document based on feedback and contributor concerns, so this isn't the final word on style.
> Add initial contributor guide

- source/installing.rst
In the installing.rst document the bullet point, "Securely Download get-pip.py" contains an out of date link. I've updated it to use https://bootstrap.pypa.io/get-pip.py rather then https://raw.github.com/pypa/pip/master/contrib/get-pip.py
> Fix broken URL

- source/distributing.rst
This change presents twine as a CLI option for registration as well.
It also moves the note about manual .pypirc creation to the section
on creating an account, as that is needed for `twine register` to work.
> Cover package registration via twine

- source/index.rst
- source/specifications.rst
Add a dedicated specifications section, allowing the following:
* noting all currently active PEPs in one *.python.org location
* recording caveats on PEPs that have been partially, but
not wholly, superseded by other PEPs
* noting cases where current real world practice differs from
the details of older PEPs from the era when distutils was
still the reference implementation for packaging
> Add specifications section

- source/specifications.rst
[...]/source/specifications.rst:93: WARNING: Inline emphasis start-string without end-string.
> Fix a Sphinx warning in specifications.rst

- README.rst
* Python is a proper noun
* "Hitchhiker's" needs a possessive apostrophe
* "Thankyou" is two words, not one
> Grammar fixes in README

- source/installing.rst
Clarify that pyvenv is available on Python 3.3+ and virtualenv supports Python 3.5.
Also, updated to use "through" instead of "thru".
> Update virtualenv and pyvenv information in installing.rst

- source/distributing.rst
- source/glossary.rst
- source/installing.rst
- source/multi_version_install.rst
- source/pip_easy_install.rst
- source/projects.rst
The setuptools docs appear to have moved, and the old location doesn't work (at least at this time). Update all references to them (using https, and after checking they're still up to date).
> Update references to the setuptools docs

- source/distributing.rst
Issue ##231 indicated it is unclear where dist/ directory comes from or where to find it. Clarifying this situation so folks can register and upload their files to PyPI.
> Explaining where dist/ comes from

- source/distributing.rst
Per Twine issue 177. https://github.com/pypa/twine/pull/177 Also, corrected how to register, to clarify you must specify the file, not use glob. Per Twine issue 176. https://github.com/pypa/twine/pull/176
> Update PyPI url to Warehouse

- source/distributing.rst
Right now the sentence as it renders on the webpage is missing a word:
I simply added the word "page" to complete the sentence.
> Minor wording change for clarity

- source/distributing.rst
We had a non-English speaker in #pypa asking about why the documentation seems to imply that `pip install -e` doesn't install dependencies.  Rewrite this to make it clear that dependencies will be installed, but --editable will have no effect on them.
> Clarify confusing sentence

- source/key_projects.rst
warehouse.python.org redirects to pypi.org, so let's update the links too.
> Update warehouse link to pypi.org

- source/specifications.rst
While not yet implemented in pip, the base pyproject.toml format
definition has been accepted.
> Add PEP 518

- source/distributing.rst
* Add missing colon to make PEP-link work
> Fix typo in distributing.rst

- source/distributing.rst
If sdist was invoked before bdist_wheel - upload first tries sdist upload
and some metadata on pypi will be missing (notable, Requires
Distributions section).
c.f.
```
$ python setup.py sdist bdist_wheel upload -r https://pypi.python.org/pypi
[...]
running upload
Submitting dist/Diofant-0.8.0a2.tar.gz to https://pypi.python.org/pypi
HTTP Error 400: This filename has previously been used, you should use a different version.
error: HTTP Error 400: This filename has previously been used, you should use a different version.
```
vs
```
$ python setup.py bdist_wheel sdist upload -r https://pypi.python.org/pypi
[...]
running upload
Submitting /home/sk/src/diofant/dist/Diofant-0.8.0a2-py3-none-any.whl to https://pypi.python.org/pypi
HTTP Error 400: This filename has previously been used, you …
```
> Fix order of setup.py arguments for upload command

- source/deployment.rst
- source/extensions.rst
- source/installing.rst
- source/key_projects.rst
- source/mirrors.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified. Some redirected to newer URL's so I've replaced them with their redirect targets.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- source/distributing.rst
Installing project and dependencies in editable mode using local directories, not vcs, using current instructions does not work. The local directory is found, but then the dependency is overridden and fulfilled by PyPI. Changing the order of the editable mode dependencies (i.e. putting editable mode dependencies which reside in local directories at the top of the requirements file) fixes this problem.
> Update distributing.rst "Development mode" section

- source/additional.rst
- source/namespace_packages.rst
> Add topic on namespace packages

- source/additional.rst
- source/plugin_discovery.rst
> Add topic on plugin discovery

- source/distributing.rst
> Remove "twine register" reference in distributing.rst

- source/contribute.rst
- source/index.rst
This PR adds a contributing and style guide started on the `develop` branch (with a few edits). Based on the discussion with @jonparrott from #301, this is the first step in retiring the `develop` branch. Some of this doc is based on conventions that I've seen elsewhere in the guide, other bits are aspirational (e.g., headings use different styles in different places, so I tried to aim for easier to explain and maintain). I'm happy to make any changes needed to get this into mergeable state.
> Add initial contributor and style guide

- source/specifications.rst
This allows specifying the content type of the distribution's description (e.g.: `text/plain`, `text/x-rst`, `text/markdown`).
See https://github.com/msabramo/python-packaging-user-guide/blob/description-content-type/source/specifications.rst#description-content-type
Cc: @nicktimko, @ncoghlan, @dstufft, @jaraco, @xavfernandez 
Related:
- https://mail.python.org/pipermail/distutils-sig/2016-May/028689.html
- https://github.com/pypa/readme_renderer/pull/3
- https://github.com/pypa/setuptools/pull/708
> Add Description-Content-Type field

- source/index.rst
- Move tutorials links into bullet points to help them stand out
- add a link to the Tutorials overview from the Get Started section
- use "the &lt;thing&gt;" section in a few places where just saying "&lt;thing&gt;"
results in some slightly awkward phrasing
> Adjust landing page layout

- source/index.rst
There appears to have been a copy-and-paste error that lead to a `>` being included at the end of the URL for the "This guide is maintained on GitHub" link on the main page.  This fixes that.
> Fix link-breaking typo

- source/tutorials/distributing-packages.rst
Rather than referring readers to a PEP via a link that doesn't even go to the right part of the page, this patch incorporates the salient points on project names from PEPs 426 and 503 into the section on the `name` argument to the `setup()` function.
> Expand the section on the "name" argument

- README.rst
* Move the historic acknowledgement and license statements to their own sections at the end
* Put the URL to the guide immediately after the heading
* The guide is maintained by PyPA doesn't need to be mentioned (it's under the pypa org)
> Format the README file

- source/tutorials/distributing-packages.rst
> Note that MANIFEST.in does not affect wheels

- scripts/linkmonitor/ignored.yaml
- scripts/linkmonitor/linkmonitor.py
- source/new-tutorials/index.rst
Context: https://github.com/pypa/python-packaging-user-guide/issues/301#issuecomment-310714081
This required a few changes to the linkchecker so I can tell it to ignore the section altogether.
> Add a staging area for new tutorials

- source/guides/index.rst
- source/guides/migrating-to-pypi-org.rst
Feel free to edit this to be worded better. This is to support https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html and I hope to link to this to instruct people how to migrate. If we're able to get this merged today that would be awesome.
> Add a document on migrating uploads to PyPI.org

- source/guides/migrating-to-pypi-org.rst
After reconfiguring clients to use `pypi.org` for uploads,
any explicit `register` calls will need to be skipped, as
the new API doesn't allow them.
> Note removal of explicit registration API

- source/guides/migrating-to-pypi-org.rst
The trailing `/` is important, as I found out in https://github.com/takluyver/flit/issues/122
Without the trailing `/`:
`~/.pypirc` file:
```
[testpypi]
repository = https://test.pypi.org/legacy
```
output:
```
$ twine upload -r testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy
Uploading cherry_picker-0.0.3.post3-py3-none-any.whl
RedirectDetected: "https://test.pypi.org/legacy" attempted to redirect to "https://test.pypi.org/legacy/" during upload. Aborting... 
```
With the trailing `/`:
`~/.pypirc` file:
```
[testpypi]
repository = https://test.pypi.org/legacy/
```
output:
```
$ twine upload -r testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Uploading cherry_picker-0.0.3.post3-py3-none-any.whl
Uploading cherry_picker-0.0.3.post3.tar.gz …
```
> Add trailing "/" to testpypi url

- source/guides/index.rst
- source/guides/using-testpypi.rst
> Add a guide on how to use TestPyPI

- source/tutorials/installing-packages.rst
Mercurial repositories does not have the .git suffix, so we should not use it on the example mercurial url.
> Remove .git suffix from mercurial repository

- source/new-tutorials/installing-and-using-packages.rst
Reading the code for @ofek's `pybin` utility reminded me
that `python -m site` accepts options to display just the
particular setting that you're interested in instead of showing
all of them.
> Recommend the `--user-base` option

- source/tutorials/distributing-packages.rst
`python setup.py check --restructuredtext` did not report any errors, but `readme_renderer` explained effectively and concisely that `.. raw::` directives are not allowed.
1. I didn't know what to do for the admonition.  I think it's in the right section, but there was already a `note` and a `warning`, and the `pypa_theme` doesn't seem to stylize `tip` or `danger` (sphinx only?).
- I could also make it a definition list under `**Tip**`?
2. Happy to change any and all verbiage.  I just feel like linking to this tool directly will save a lot of people time, and reduce burden on PyPI from people who are releasing versions just to try and get the long description to show up.
- I'll confess this was me, but internet trolling seems to reveal it's not uncommon.  I can't use `testpypi` for some …
> encourage RST checking with readme_renderer

- source/guides/using-testpypi.rst
Fix typo in using-testpypi.rst.
> Fix typo in using-testpypi.rst: add missing "is"

- source/guides/using-testpypi.rst
- source/tutorials/distributing-packages.rst
distributing-packages.rst has an outdated link to https://wiki.python.org/moin/TestPyPI which links back to https://packaging.python.org/guides/using-testpypi/
better make that a real internal link
> update link from distributing-packages.rst to using-testpypi.rst

- source/guides/index.rst
- source/guides/installing-using-pip-and-virtualenv.rst
- source/new-tutorials/installing-and-using-packages.rst
This moves the current ["Installing Packages" tutorial](https://packaging.python.org/tutorials/installing-packages/) into a guide and updates some of the wording and recommendations.
Once this is merged, I will delete the current tutorial and replace it with the `pipenv` tutorial presently in `new-tutorials`.
> Move existing installing packages tutorial into a guide

- source/specifications/core-metadata.rst
- source/specifications/entry-points.rst
- source/specifications/index.rst
As discussed on the distutils-sig mailing list, I would like entry points to be documented as an interoperable standard. I have a particular interest in this as I've written implementations of both creating entry points (flit) and loading them (entrypoints).
This is my attempt to document the entry points mechanism as it already exists, based on reading code and the [pkg_resources API docs](http://setuptools.readthedocs.io/en/latest/pkg_resources.html?highlight=pkg_resources#creating-and-parsing).
> Add a specification of the entry_points.txt file

- source/guides/appveyor-sample/appveyor.yml
AppVeyor now supports Python 3.6.3
> Add C:\Python36-x64 to AppVeyor sample

- source/tutorials/distributing-packages.rst
> Document py_modules

- source/key_projects.rst
The previous link to Pipenv documentation was broken. Replaced for https://docs.pipenv.org
> Fixed broken link for Pipenv docs.

- source/key_projects.rst
- source/tutorials/distributing-packages.rst
Now that wheel is on GitHub, I updated the links in the Project
Summaries.  I also found one link that pointed to the (now-removed)
issue tracker on BitBucket, and changed it to the corresponding issue
on GitHub.
> wheel is now on GitHub

- source/discussions/deploying-python-applications.rst
- source/discussions/install-requires-vs-requirements.rst
- source/discussions/wheel-vs-egg.rst
- source/glossary.rst
- source/guides/installing-scientific-packages.rst
- source/guides/supporting-multiple-python-versions.rst
- source/key_projects.rst
Per the [style
guide](https://devguide.python.org/documenting/#capitalization).
Instances involving URLs, commands, etc. were not modified.
> Capitalize "Python" when describing the language.

- source/specifications/core-metadata.rst
[PEP 345](https://www.python.org/dev/peps/pep-0345/#id34) lists six fields which can have environment markers. I've noted it for all six, but I don't know if I should. In particular, I've never seen a classifier listed with an environment marker, and it doesn't make much sense to me to allow that.
I've also updated the specification of `Requires-Dist` with a brief summary of PEP 508.
Closes gh-409
> Note which fields can be used with environment markers

- source/tutorials/distributing-packages.rst
Based on discussions with @lgh2. It may not be immediately clear to new users that the distribution command must be re-run if there are changes.
@lgh2, would you mind giving a review?
> Add note about needing to rebuild changes

- source/guides/installing-using-pip-and-virtualenv.rst
- source/guides/migrating-to-pypi-org.rst
- source/guides/using-testpypi.rst
- source/tutorials/distributing-packages.rst
Be more explicit to help users who aren't as familiar with the tilde. Inspired by an experience @lgh2 had, figuring out where `.pypirc` files live:
`<lghampton>` I think it was the `~/.pypirc` syntax that confused me, it wasn't clear to me that it referred to `$HOME` or something relative to the project path
I left out instances where the tilde was explicitly explained in the paragraph where it was used (`source/tutorials/managing-dependencies.rst`, and where the tilde appeared as part of sample terminal output.
I might be wrong in proposing this PR. I'm open to being told, for instance, that we need to use `~` for platform compatibility reasons, or for uniformity with other documentation. In that case I'd like for us to explicitly mention what it means, contextually, as in …
>  Replace `~` with `$HOME` in guides, tutorials 

- source/tutorials/installing-packages.rst
The double colon was causing the `..code-block` line to be interpreted
as part of the code itself and therefore displaying in the HTML.
> Fix code block inside note.

- source/specifications/core-metadata.rst
- added a link to PyPI's list of classifers
- updated the PEP 301 reference to be a regular hyperlink
- hyperlinked the cross reference from License to Classifier
> #95: Link to PyPI's list of classifiers

- source/guides/using-testpypi.rst
This PR addresses part of [issue 422](https://github.com/pypa/python-packaging-user-guide/issues/422). 
This PR adds an explanation of the `legacy` in `test.pypi.org/legacy` and adds information on how to view your package on test.pypi.org once it has been uploaded. 
In the example of how to view the package, I use `sampleproject` as a placeholder for the project name, but I can change it if someone has an idea for a clearer name.
> Add information on how to view test packages 

- source/specifications/core-metadata.rst
This is often asked for, has always been permitted by the spec, and is now accepted as valid by Warehouse (https://github.com/pypa/warehouse/pull/2904), so let's include an example here.
> Core Metadata: Add example of multiple emails

- source/tutorials/managing-dependencies.rst
Resolves #427.
Should be reverted when https://github.com/pypa/pipenv/issues/857 is resolved.
> Add warning about managing multiple versions with pipenv

- source/guides/migrating-to-pypi-org.rst
- source/guides/tool-recommendations.rst
- continue to describe the migration on the recommendations
page, but link to the migration page for details
- merge the info from the recommendations page into the
migration page
- add a new section about user registration migrating due
to a spam attack against the legacy service
> Issue #401: Consolidate PyPI migration info

- source/key_projects.rst
- move to PyPA section of the projects list
- update links for the new repository location
Closes #437
> pipenv has migrated to PyPA

- source/guides/migrating-to-pypi-org.rst
Issue #401: update PyPI migration info to advise users on package, release management features.
> Update PyPI migration info

- source/tutorials/distributing-packages.rst
- Update PyPI user account registration link (Per https://status.python.org/incidents/mgjw1g5yjy5j PyPI , user account registration is now only allowed on pypi.org)
- Update Test PyPI link in distribution tutorial (Issue #401)
> Update PyPI links in distribution tutorial

- source/tutorials/distributing-packages.rst
`project_urls` is an allowed option to `setup()` that provides a really nice
place for maintainers to add bug tracker or funding URLs. The hope is that by
documenting the usage, maintainers will be encouraged to add more useful URLs
to their setup.py.
This ticket comes by way of https://github.com/pypa/setuptools/issues/1276 and the corresponding PR in `sampleproject` has already been merged: https://github.com/pypa/sampleproject/pull/63
> Document `project_urls` as an option to setup.py

- source/specifications/core-metadata.rst
This PR captures all changes we need to make now that [PEP 566](https://www.python.org/dev/peps/pep-0566/) is accepted.
Fixes #410, fixes #411, closes #449.
(cc @takluyver)
> Metadata 2.1 updates

- source/tutorials/distributing-packages.rst
With [PEP 566](https://www.python.org/dev/peps/pep-0566/#description-content-type-optional), the `long_description` can be Markdown with the `long_description_content_type` arg. This adds documentation for it
There were also a couple cases where filenames were enclosed with quotes rather than as code; I've changed those to be `code` as well for consistency.
See also:
* [Relevant section in PEP 566](https://www.python.org/dev/peps/pep-0566/#description-content-type-optional)
* [The CommonMark specification](http://spec.commonmark.org)
* [The Description-Content-Type field documentation in the Python
packaging documentation](https://packaging.python.org/specifications/core-metadata/#description-content-type-optional)
Note that this references the `README.md` added in pypa/sampleproject#66, …
> Added long_description_content_type

- source/guides/installing-scientific-packages.rst
- source/guides/tool-recommendations.rst
> Updated content on 'installing scientific packages' page

- source/tutorials/distributing-packages.rst
The Packaging and Distributing Projects tutorial assumes familiarity
with the Installing Packages tutorial, but links instead to the pip
Installation tutorial. This commit replaces the pip link with the link
to the Installing Packages tutorial.
> Fix 'installing packages' link in Packaging and Distributing Packages.

- source/guides/supporting-multiple-python-versions.rst
Plus http -> https on the older two.
> Add 'What’s in which Python 3.4–3.6?'

- source/tutorials/distributing-packages.rst
Warehouse is moving away from publishing GPG signatures,
and even if it wasn't, it isn't a topic for the "Publishing your first package"
tutorial.
> Remove GPG references from publishing tutorial

- source/specifications/core-metadata.rst
And remove "(optional)" from field headings. As described on distutils-sig, this was not applied accurately - its absence implied that some optional fields were required.
@ncoghlan suggested using explicit rst link targets to preserve old links to the sections, like `...#description-optional`, and I've done this.
Remaining question: is `Summary` required? It is not marked optional in any of the PEPs specifying metadata 1.0-1.2, but @dstufft says that PyPI does not require it, so it is possible to upload packages without it.
> Describe required metadata fields at the start of the spec

- source/specifications/platform-compatibility-tags.rst
Part of https://github.com/pypa/manylinux/issues/179
> Mention manylinux2010 in platform tags specification

- source/guides/migrating-to-pypi-org.rst
This updates the guide to add instructions for interacting with PyPI.  I have left the instructions on how to update .pypirc and the error message when registering project names, so if people have problems the solutions will hopefully show up when they search for them. 
When I was writing this I assumed, please correct me if I am wrong, that ``pypi.python.org`` had already been redirected and that ``pypi.org`` was the default for downloading packages.
> adds instructions for Warehouse

- source/tutorials/distributing-packages.rst
The previous wording didn't make it clear that this step remains
the same regardless of whether or not this is the first release for
a project.
It also suggest that only twine auto-registered projects, which
is no longer the case - Warehouse *only* offers auto-registration.
Partially addresses #114 (a full resolution will require more guidance
on managing version numbers)
> Reword uploading section in tutorial

- source/guides/migrating-to-pypi-org.rst
Per https://mail.python.org/mm3/archives/list/distutils-sig@python.org/thread/YREMU56QKRMTTFBFVFJ2B4EHOEKOJZFJ/ .
> Remove pointer to now-sunset legacy PyPI

- source/tutorials/distributing-packages.rst
This is a reboot of #212.
I no longer mention distutils at all and the fact that `data_files` only works with relative paths is stated as fact, not as possible bug.
> Fix section on data_files

- source/tutorials/managing-dependencies.rst
- explain how the alternatives differ from pipenv
- add poetry to the list of alternatives to consider
> Update alternate app dep manager recommendations

- source/tutorials/managing-dependencies.rst
- move the link to the next tutorial above the list of alternatives
- explicitly mention `pipenv install -e <path>` for apps that define their own Python packages
- significantly revise the reference to poetry
> Revise "Next Steps" for app dependency management

- nox.py
- requirements.txt
- source/guides/distributing-packages-using-setuptools.rst
- source/guides/index.rst
- source/index.rst
- source/key_projects.rst
- source/tutorials/index.rst
- source/tutorials/packaging-libraries.rst
- source/tutorials/packaging-projects.rst
Move the existing tutorial into guides/distributing-packages-using-setuptools to be cleaned up later.
Staged: http://temp.theadora.io/pypug/tutorials/packaging-projects.html
Resolves #494 
Resolves #298 
Resolves #203
> Create new, simpler packaging tutorial

- source/tutorials/managing-dependencies.rst
> Remove outdated warning about Python version mixing with Pipenv

- source/guides/tool-recommendations.rst
Metadata 2.0 isn't upcoming anymore: it's here in the form of the
metadata 2.1 fields defined on the core metadata page.
> Update setuptools recommendation footnote

- source/tutorials/packaging-projects.rst
Closes https://github.com/pypa/packaging-problems/issues/153
> Fix bad filename for README in packaging tutorial

- source/key_projects.rst
Follow-up of https://github.com/pypa/python-packaging-user-guide/pull/408
> Wheel is no more on bitbucket

- source/tutorials/managing-dependencies.rst
The key design distinction between pipenv and poetry isn't
the overall scope of the projects, but rather the assumptions
we make about how projects are going to be structured.
pipenv focuses mainly on "git push" and "git archive" style
publication, where there's a private distribution pipeline
between the repo and production systems (e.g. this is
really common in SaaS and embedded systems).
poetry, by contrast, focuses on the case where a pyproject.toml
file is already present, at which point having Pipfile as well (as
`pipenv` requires if you want to use it to manage development
and testing environments) may feel redundant.
Closes #506
> Reword cross-reference to the poetry project

- source/specifications/core-metadata.rst
The design of Provides-Dist and Obsoletes-Dist was lifted pretty
much directly from the design of Linux system package managers,
without accounting for the fact that Linux distro repos are collaboratively
maintained curated collections of packages with the ability to make
repository wide changes, while PyPI is an open publishing platform
with few practical restrictions other than size quotas and the default
first-come-first-served policy on claiming names.
https://github.com/pypa/packaging-problems/issues/154
> Note issues with Provides-Dist and Obsoletes-Dist

- source/tutorials/installing-packages.rst
Fixes #407 
To accurately distinguish between Jupyter shell and kernel interactions, change existing python system command to its Jupyter variant.
Wrap the paragraph about Jupyter notebook into a separate note.
> Modify system command to account for Jupyter notebook

- source/guides/creating-and-discovering-plugins.rst
Fixed broken hyperlinks for `Flask` and `Flask-SQLAlchemy` targeted texts appearing in [Creating and discovering plugins](https://packaging.python.org/guides/creating-and-discovering-plugins/) guide.
Fixes #523
> Redirect to respective PyPI projects' URL

- source/guides/making-a-pypi-friendly-readme.rst
Added a note about requirements for Markdown descriptions on PyPI.
Fixes #481
> Explain specific requirements for Markdown descriptions

- source/specifications/index.rst
https://www.pypa.io/en/latest/specifications/ splits up the
default BDFL-Delegate based on the kind of interface a
PEP defines, and uses anchors on this page to summarise
the distinction.
> pypa.io expects two categories of interop PEP

- source/guides/installing-scientific-packages.rst
- source/key_projects.rst
xref: https://www.anaconda.com/blog/company-blog/continuum-analytics-officially-becomes-anaconda/
> Continuum Analytics changed its name to Anaconda

- source/tutorials/installing-packages.rst
Virtualenv 16.0.0 dropped support for Python 2.6
https://virtualenv.pypa.io/en/stable/changes/
> Update Python version supported by virtualenv

- source/news.rst
The news page had not been updated since November 2017. The git commit logs were used to populate the page.
Please let me know if there are any unnecessary news bits. I included everything except typo fixes but if there are others that should be removed I can do so.
> Update news page from December 2017 to July 2018

- source/index.rst
This moves the overview that was added in #519 from a dedicated call out at the start of the "Get Started" section, into the list of task based documents.
The overview document is not the globally correct choice for users hitting this page who want to get started-- often these users will be looking for a simple tutorial that just tells them what to do rather than a deep dive into all of the various options they *could* pick. The new location brings these different tasks ("I want an overview" vs "I want to package software" vs "I want to manage dependencies for an application" vs "I want to install software") back into alignment with each other, and generally fits the overall feel of python.packaging.org better.
> Move the Overview to a task based lead in along with the others

- source/index.rst
Reopening #541 post-squash freshening, quoth:
> While I appreciate the expeditious velocity in #540, I agree with @dstufft that the wording needs some work. The overview does not cover "Python's packaging options", but rather "options for packaging Python libraries and applications". In fact, most of the options do not originate from official Python efforts or groups.
TLDR: "an overview of Python's packaging options" -> "an overview of packaging options for Python libraries and applications"
> Clarify that the overview also covers non-Python packaging options

- source/tutorials/packaging-projects.rst
> Fix tutorials/packaging-project's setup.py example to specify classifiers as a list.

- source/guides/using-testpypi.rst
For https://github.com/pypa/python-packaging-user-guide/issues/297#issuecomment-413790391
> Remove the recommendation to store passwords in clear text.

- source/specifications/index.rst
Without a backlink from the specifications page to the process
page, it isn't obvious how things currently work.
> Link back to the spec process page

- source/tutorials/installing-packages.rst
- source/tutorials/managing-dependencies.rst
The instructions for how to update `PATH` for `--user` installs belong in the section on `--user` installs, not in the Pipenv section.
> Move note on PATH to --user installs section

- source/guides/dropping-older-python-versions.rst
In the "Dropping support for older Python versions" guide, the tar command given for showing the sdist's metadata does not work (unless you happen to run it in your project directory without cleaning up your `.egg-info` dir first, in which case it only works by accident and the `tar` is pointless).  This pull request changes the command to something that does work.
> Replace tar command with something that works

- source/guides/distributing-packages-using-setuptools.rst
I felt the wording of the sections on `packages` and `py_modules` could be improved.  I also felt the two sections belonged right next to each other.
> Improve `packages` and `py_modules` wording

- source/guides/making-a-pypi-friendly-readme.rst
This PR adds a section to "Making a PyPI-friendly README" describing how to use `readme_renderer` to check that a reStructuredText README renders correctly.
> Added a section on checking RST markup

- source/guides/making-a-pypi-friendly-readme.rst
I thought I was doing the right thing by including [Sphinx cross-references](http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing-python-objects)
in my `README.rst` and through that in my package's `long_description`, but only after
several failed validations and searching did I learn that Sphinx extensions are not allowed.
The error message from `twine check` (or `rst-lint`) is not obvious about what is wrong: e.g.,
'Error: Unknown interpreted text role "py:func".' and to those just figuring out Sphinx and rST
the distinction is not necessarily obvious.
(I am submitting this PR against "master" because the other 2 open PRs do that; I read the contributing guide but it gave no advice about which branch to use.)
> Mention not using Sphinx extensions in "Making a PyPI-friendly README"

- source/tutorials/creating-documentation.rst
- source/tutorials/index.rst
Responding to Issue https://github.com/pypa/python-packaging-user-guide/issues/484
> Creating documentation

- source/guides/single-sourcing-package-version.rst
Add `setuptools` as an example of single-sourcing package versioning using `pkg_resources`.
> Add example for single-sourcing pgk ver using pkg_resources

- source/guides/single-sourcing-package-version.rst
Change the bumpversion to bump2version in the list of tools to manage version.
Bumpversion has not received an update since 2015. [bump2version](https://pypi.org/project/bump2version/) is a fork that is being maintained.
The maintainer of bumpversion has stated
>I should probably add a sunsetting notice to the top of the README, saying this is not actively maintained and people should switch to one of the forked versions.
--https://github.com/peritus/bumpversion/issues/169#issuecomment-339023681
> Change bumpversion to bump2version

- source/index.rst
The migration is complete. ;)
I've let the guide stay, as a historical record. I don't think it'd serve much use though now, since the migration is over, so I'll be happy to delete the file if that's what we want to do.
> Remove landing page link to PyPI migration guide

- source/tutorials/packaging-projects.rst
The tutorial begins by instructing the reader to create this confusing hierarchy without explanation:
```
example_pkg/
example_pkg/
__init__.py
```
The tutorial then continues on, referring to `example_pkg` frequently, but not clarifying _which_ one is meant. Confusing! And not necessary, in my opinion. So this PR renames the top-level dir, better describing its purpose:
```
packaging_tutorial/
example_pkg/
__init__.py
```
> Add more clarity to the packaging tutorial dir structure

- source/tutorials/packaging-projects.rst
pip doesn't necessarily add it to the path.
> Reference twine from Python3

- source/guides/single-sourcing-package-version.rst
This file has been removed, but we could still link to the historical version.
> Update link to __about__ example

- source/tutorials/packaging-projects.rst
In some operations systems such as mine (macOS Mojave 10.14 Beta (18A365a)), after installing twine the system can not find twine unless you call it explicatively.
> Fix tutorials/packaging-project's twine example

- source/guides/appveyor-sample/appveyor.yml
At 2018 AppVeyor on Linux [**is available**](https://www.appveyor.com/blog/2018/05/15/appveyor-for-linux-is-generally-available/). List of pre-installed software will be split:
+ [**Windows**](https://www.appveyor.com/docs/windows-images-software)
+ [**Linux**](https://www.appveyor.com/docs/linux-images-software)
I replace old broken link to link, specific for Windows.
Thanks.
> fix(link): replace dead link to active

- source/guides/index.rst
- source/guides/installing-stand-alone-command-line-tools.rst
- source/key_projects.rst
- source/tutorials/installing-packages.rst
pipx (https://github.com/cs01/pipx) is a command execution tool like pipsi, and was mentioned in this thread.  https://github.com/pypa/python-packaging-user-guide/issues/406
Pipsi is no longer maintained, and pipx (my project) hopes to pick up where pipsi left off. 
I took a shot at adding a section to the installation tutorial. I think this type of tool provides a lot of value to the python community yet doesn’t seem to be very well known. Hopefully this will change that 😄 .
> add instructions to install python CLI applications with pipx

- source/tutorials/packaging-projects.rst
This addresses [this issue](https://github.com/pypa/packaging-problems/issues/246). It is meant to help people who want to use the tutorial as a scaffold for getting their own package onto PyPI to understand what steps are required and which ones are just for the tutorial.
> Elaborate on how the tutorial differs from the real packaging process

- source/guides/single-sourcing-package-version.rst
Thanks for this guide! I was using this and tried `execfile()` without realizing it didn't work in Python 3.
I thought about leaving the Python 2 version here with a disclaimer, though this list is already very long, and it seems more helpful to steer people toward a good solution than to exhaustively document an obsolete solution.
I simplified the Python 3 option to a version which seems equally safe without the context handler (it seems the file handle should be closed when it goes out of scope), which should be immediately upon return.
> SIngle-sourcing the package version: Remove a py2-only option; simplify a py3 option

- source/guides/index.rst
- source/guides/installing-using-pip-and-virtual-environments.rst
- source/tutorials/installing-packages.rst
* Replace use of `virtualenv` with `virtual environment` when referring to a virtual environment 
* Only use the term `virtualenv` when referring to the tool. 
* Recommend venv over virtualenv. Make it clear that venv is preferred for Python 3.
> reduce emphasis on virtualenv

- source/guides/distributing-packages-using-setuptools.rst
- source/guides/index.rst
- source/guides/using-manifest-in.rst
This pull request adds a guide to using `MANIFEST.in` files, including information on files included & excluded from sdists by default.
> Guide to MANIFEST.in

- source/tutorials/packaging-projects.rst
Updating documentation based off discussion at the Python Packaging Summit during PyCon 2019. Should address #612
> add python_requires usage to example

- source/specifications/entry-points.rst
Issue #458 introduced minor formatting errors in `entry-points.rst`, when it changed 
```
``foobar.txt``
```
to
```
:file:``foobar.txt``
```
The correct version is
```
:file:`foobar.txt`
```
> Fix :file:``filename`` instances

- source/tutorials/packaging-projects.rst
Directory layout examples were changed to use trailing slashes.
Rationale:
* consistent with examples in the Python [modules tutorial](https://docs.python.org/3/tutorial/modules.html#packages)
* consistent with example currently on line 208 (dist/) 
* removing the first leading slash avoids possible confusion that you are to work in the root directory
> Change directory layout examples for consistency

- source/guides/packaging-namespace-packages.rst
packaging-namespace-packages.rst previously recommended listing all packages manually.
This function is available since [setuptools v4.0.1](https://setuptools.readthedocs.io/en/latest/history.html#v40-1-0) from 17 Aug 2018.
> Mention find_namespace_packages

- requirements.txt
- source/conf.py
pypa.io's cert is invalid, but it doesn't matter as we're not actually using its intersphinx inventory for anything.
> Upgrade Sphinx version, remove pypa.io intersphinx

- source/guides/installing-stand-alone-command-line-tools.rst
As noted in https://github.com/pypa/packaging.python.org/pull/607, `pipx` may not be on the user's PATH when installed with the `--user` flag. This PR adds the `python3 -m` prefix when ensuring the PATH has paths pipx expects. Note that pipx now considers `ensurepath` best practice again (it's no longer deprecated).
> use python3 -m when installing pipx

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
- source/guides/index.rst
- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
Resolves pypa/gh-action-pypi-publish#2
> Add a guide about publishing dists via GH Actions

- source/tutorials/packaging-projects.rst
> Clarify default --repository-url for 'real' PyPI

- source/tutorials/packaging-projects.rst
I added the word 'be' in the sentence, "It also must not already *be* taken on pypi.org."
> Added missing text to fix the sentence

- source/specifications/platform-compatibility-tags.rst
Updates the section on `manylinux` per https://github.com/pypa/manylinux/issues/179 and https://github.com/pypa/manylinux/issues/338.
> Update manylinux tags section

- source/specifications/core-metadata.rst
Every other example in the guide has the field name included in the example, I think it was likely just an oversight that this one was missing it.
> Add field name for the Project-URL example

- source/guides/installing-using-pip-and-virtual-environments.rst
- source/tutorials/managing-dependencies.rst
Closes #648 -- we don't actually need to link to the documentation here (or to anything at all, really, but we do).
> Fix broken links

- source/specifications/core-metadata.rst
distutils and setuptools have gone against the spec for years, possibly without anyone noticing. Changing the spec to record what's in widespread use is much easier than trying to fix the tools to match the spec.
Discussion on distutils-sig: https://mail.python.org/archives/list/distutils-sig@python.org/thread/LFTLGMIIB5PRG7NUUIGGGX4COGX53DMR/
> Change keywords field to be comma separated

- source/discussions/deploying-python-applications.rst
Early versions of Pynsist worked as this note described before, but then an [option to bundle Python](https://pynsist.readthedocs.io/en/1.12/cfgfile.html#bundled-python) was added, then made the default, and has been the only mechanism supported since Pynsist 2.0, 2 years ago.
> Update description of how Pynsist installs Python

- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
This PR removes a public beta warning from the GitHub Actions guide as GH actions is publically available and no longer in beta (ref https://github.blog/changelog/2019-11-11-github-actions-is-generally-available)
> Remove GH actions beta warning

- source/contribute.rst
This PR contains a small update to the "Purpose" subsection of the contributing page, which is currently rendered as a block quote:
Happy to close this PR if this formatting is intended
> Update contributing purpose formatting

- source/guides/using-manifest-in.rst
setuptools 42.0.0 introduces support for including files specified with the `license_files` option.  This PR updates the list of files included in a source distribution by default to reflect that.
> Update sdist default contents list for setuptools 42.0.0

- source/guides/using-manifest-in.rst
setuptools 43.0.0 now automatically includes `pyproject.toml` in sdists.  This PR updates the list of files included in a source distribution by default to reflect that.
> Update sdist default contents list for setuptools 43.0.0

- source/guides/distributing-packages-using-setuptools.rst
- source/tutorials/packaging-projects.rst
API tokens are now a production feature of PyPI and users should use them instead of passwords to upload.
Toward #628. Also related to https://github.com/pypa/warehouse/issues/6211 and https://github.com/pypa/warehouse/issues/5661#issuecomment-515802931 (the final step for getting the API token feature out of beta so I can announce it on `pypi-announce`).
Signed-off-by: Sumana Harihareswara <sh@changeset.nyc>
> Instruct users to upload to PyPI with tokens

- source/key_projects.rst
- source/specifications/index.rst
A few link fixes, clearer explanations regarding wheel, packaging, pip, and distlib, and a few wording/capitalization fixes.
> Update wording, links in key projects page

- source/key_projects.rst
Thanks to @brainwane for adding piwheels to key projects in #691. Just wanted to propose a couple of small changes:
- un-capitalise Piwheels -> piwheels
- use canonical url "**www**.piwheels.org"
- change "some devs use piwheels as primary index" -> "Raspbian is pre-confiigured to use piwheels as an additional index"
> Edit piwheels section of key projects

- source/specifications/entry-points.rst
> Fix invalid regex for entry point names

- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
The current guide links to [pypa/gh-action-pypi-publish](https://github.com/marketplace/actions/py-package-publish) with both the name and URL in the link text. This is unnecessary, as you can mouseover the link to see the full URL anyway. This commit improves readability by removing the URL portion from the link text.
This is what the [web version of the guide](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) currently looks like:
>It will use the [pypa/gh-action-pypi-publish GitHub Action https://github.com/marketplace/actions/pypi-publish](https://github.com/marketplace/actions/pypi-publish)
This commit changes it to:
>It will use the [pypa/gh-action-pypi-publish GitHub …
> Don't show full URL to gh-action-pypi-publish in anchor text

- source/guides/single-sourcing-package-version.rst
Item 5 in ["Single-sourcing the package version"](https://packaging.python.org/guides/single-sourcing-package-version/) currently presents its approach using `pkg_resources`.  However, `pkg_resources` is inefficient (and possibly deprecated?), and more efficient & modern alternatives to it are being developed in the form of `importlib.resources` and `importlib.metadata`.  This PR extends item 5 to also show how to achieve the same thing using `importlib.metadata`.  It also adds a note that the `pkg_resources` version requires `setuptools` as a runtime dependency.
I expect there will be some debate over whether to present both methods side by side or whether to delete the `pkg_resources` method in favor of `importlib.metadata`.  I'm open to both possibilities.
> Describe using importlib-metadata as an alternative to pkg_resources for single-sourcing versions

- source/key_projects.rst
Rewrite Flit's description to reorganize sentences, improve wording, increase readability. The 1st paragraph describes what Flit is and what it can do. The 2nd paragraph describes how it works and what is needed (or not) to use Flit.
Also add a link to Flit's rationale ("[Why use Flit?](https://flit.readthedocs.io/en/latest/rationale.html)"), as requested by #702. (This was the original goal, but I figured a full rewrite was needed anyway.)
Fixes #702.
> Update flit description & add link to rationale

- source/tutorials/managing-dependencies.rst
- source/tutorials/packaging-projects.rst
* set public deadline for tutorial removal if the pipenv release doesn't happen
* emphasise poetry more as an option for library developers (and developers
of applications that can be distributed as libraries)
* update GitHub URL for poetry project
> Issue #701: Note pipenv project maintenance problems

- source/guides/using-testpypi.rst
- source/tutorials/packaging-projects.rst
Since Twine provides defaults for `pypi` and `testpypi`, it seems friendlier (and more maintainable) to rely on those, instead of the `/legacy` URLs. I made a similar change in https://github.com/pypa/twine/pull/592.
I didn't update the [migrating to pypi.org doc](https://github.com/pypa/packaging.python.org/blob/master/source/guides/migrating-to-pypi-org.rst), partially because I'm assuming it's less relevant, but also because the explicit URLs felt like useful information.
> Replace repo URLs with defaults

- source/key_projects.rst
The pipenv "Docs" link points to an expired domain (pipenv.org). This problem is acknowledged in a footnote. 
Since there now looks to be a stable official home for the docs at https://pipenv.pypa.io/ this PR proposes that the "Docs" link point there directly.
The footnote, made superfluous by the working "Docs" link, is removed.
> Update pipenv docs link and remove related footnote

- source/glossary.rst
Per https://groups.google.com/d/msg/pypa-dev/rUNsfIbruHM/LCEx-CB5AgAJ , pointing to distutils-sig and Discourse instead.
> Update link to now-decommissioned mailing list

- source/guides/distributing-packages-using-setuptools.rst
Per https://groups.google.com/d/msg/pypa-dev/rUNsfIbruHM/LCEx-CB5AgAJ
the pypa-dev Google Group is now decommissioned.
Using this opportunity to, as in
pypa/sampleproject#118, improve the example
author name and email address.
Signed-off-by: Sumana Harihareswara <sh@changeset.nyc>
> Improve sample author email and name in guide

- source/tutorials/packaging-projects.rst
Update the `Packaging Python Project` tutorial to specify the target location of the newly added package files (`tests/`, `setup.py`, `README` and `LICENSE`) to the project's root directory to remove confusion of the folder structure.
> Update Packaging Python Project Tutorial

- source/key_projects.rst
Add a description of the trove-classifiers package to the list of key projects. Closes #714.
I've made an assumption in writing the description: that readers wont know what classifiers are, and that it wont be immediately obvious(without reading the trove-classfier README) to them why you'd have a package for it instead of using the list of classifiers published on the PyPI. I copied a line off of #714 to explain what a classifier is, and suggested why you'd want to use troves-classifier(its python code, and a repo gets you an issue tracker). Do these make sense?
Any feedback (on style too)?
> Add trove-classifiers to key projects

- source/guides/distributing-packages-using-setuptools.rst
- source/guides/migrating-to-pypi-org.rst
- source/guides/using-testpypi.rst
- source/key_projects.rst
- source/specifications/index.rst
- source/specifications/pypirc.rst
Closes #730.
I'm starting this out as a draft PR, because I think a complete PR would include updates to other documents that reference `.pypirc`. However, before spending time on that, I'd like get the content of this document approved.
> Add .pypirc specification

- source/specifications/pypirc.rst
Inspired by "Securing The .pypirc File" at
https://truveris.github.io/articles/configuring-pypirc/
> Recommend permissions for .pypirc

- source/tutorials/managing-dependencies.rst
The pipenv team hit their April and May release targets, so the caveat about the seeming impasse of pipenv development no longer applies. However, it may benefit the user to know that the early access version of the package is available as pre-release in `pip`.
> Remove pipenv "state of project" caveat

- source/specifications/core-metadata.rst
It's not clear what a "sign" is meant to be – "character" isn't unambiguous, but it at least matches the text of the PEP.
> Clarify wording about length of Project-URL

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
Removed `event` from `github.event.ref` as per ticket.
Fixes #742.
> Updated if condition as per ticket

- source/glossary.rst
Also, add the pyproject.toml and setup.cfg markers as other possible "marker" files for a "practical way to define projects".
---
The [project](https://packaging.python.org/glossary/#term-project) entry is currently outdated. Here's my suggestion for updating it.
(Is a PR is the right way to suggest the change, or should I discuss on Discourse first?)
> Update "project" to mention pyproject.toml, not just setuptools

- README.rst
- source/contribute.rst
For details, see:
* https://discuss.python.org/t/implementing-pep-609-pypa-governance/4745
> The PyPA has adopted the PSF code of conduct

- source/guides/single-sourcing-package-version.rst
This PR adds a note to the `setup.py`-parsing option for single-sourcing project versions that setuptools' `attr:` directive does the same thing (without importing dependencies) starting in version 46.4.0.
> Mention enhanced attr: directive in single-sourcing option #1

- source/specifications/distribution-formats.rst
- source/specifications/recording-installed-packages.rst
Hello,
This is my proposed update to "Recording installed distributions", moving from [PEP 376](https://www.python.org/dev/peps/pep-0376/) to a specification under PyPA.
See:
* [The PEP](https://github.com/python/peps/blob/master/pep-0627.rst) (currently in a PR) for the rationales;
* the [Discourse thread](https://discuss.python.org/t/pep-627/4126) for discussion;
* the [added page](https://github.com/encukou/packaging.python.org/blob/pep-627-recording-installed-projects/source/specifications/recording-installed-packages.rst) rendered by GitHub.
This should not be merged until the PEP is accepted, but the proposal needs to be available while the PEP is reviewed.
Edit (ncoghlan): Updated PEP link to refer to the merged PEP
> PEP 627: Recording installed projects

- source/specifications/core-metadata.rst
Cf https://github.com/pypa/setuptools/issues/1876 for context and https://github.com/pypa/setuptools/issues/1876#issuecomment-545642504 specifically for the reasoning.
TLDR: PEP-0345 currently allows environment markers for `Requires-Python` but most tools do not expect environment markers to be present in this field: let's update the specification/PEP to match the reality.
This would also require (?) an update to PEP-0345 (simply remove https://github.com/python/peps/blob/5a0ab0c2b71441f839914df6e7b996bfc4850cab/pep-0345.txt#L499).
> specifications: Requires-Python doesn't accept an environment marker

- source/discussions/pip-vs-easy-install.rst
_Note:_ I actually don't know what pylauncher is, so if Vinay's project is not the right one then apologies
The setuptools docs also have the same broken link here https://setuptools.readthedocs.io/en/latest/easy_install.html#natural-script-launcher
> Fix broken link in user guide

- source/key_projects.rst
piwheels now honours the Requires-Python attribute on files, so I've removed the warning from the key projects page. 🚀 
https://blog.piwheels.org/requires-python-support-new-project-page-layout-and-a-new-json-api/
I also changed "Raspbian" to "Raspberry Pi OS" as the project name has [changed](https://www.raspberrypi.org/downloads/raspberry-pi-os/).
> Remove Requires-Python warning from piwheels project description

- source/guides/analyzing-pypi-package-downloads.rst
> update PyPI package download queries to use file_downloads table

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
See https://github.com/pypa/pep517/issues/91
Signed-off-by: Filipe Laíns <lains@riseup.net>
> guides: replace pep517 CLI usage with pypa/build

- source/glossary.rst
The current link to the _Internal Structure of Python Eggs_ page is broken.
> Update link to egg format

- source/guides/distributing-packages-using-setuptools.rst
The link on https://packaging.python.org/guides/distributing-packages-using-setuptools/#entry-points for "Dynamic Discovery of Services and Plugins" is going to the wrong place
> fix orphaned link

- source/tutorials/packaging-projects.rst
On Windows, default file encoding is not UTF-8 in most environments.
> Use utf-8 to read README

- source/discussions/pip-vs-easy-install.rst
The "easy_install" references links to a section with "setuptools" as
the title. This title is then used as the link text, making the section
incomprehensible for people not familiar with the relationship between
pip, easy_install, and setuptools.
> Fix references with wrong link text

- source/guides/index.rst
Split the toctree of guides into three broad categories:
- Installing Packages
- Includes guides for installing and managing dependencies.
- Building and Publishing Projects
- Includes guides for project configuration, distribution
- Miscellaneous
- Guides that do not clearly fit into any of the above
This commit primarily affects the Guides index page; it does not create nested lists for each category in the sidebar.
> Organize index of guides into 3 categories

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
GitHub seems to default to uppercase nowadays, and in PyPI terms
this is about API tokens instead of passwords as such.
Refs https://github.com/pypa/gh-action-pypi-publish/pull/52#pullrequestreview-550969422
> Refer to PyPI API tokens as such in GitHub secret names, spell in uppercase

- source/tutorials/installing-packages.rst
This flips the order of "synonym" vs "meaning", to convey the meaning before using
a loaded term that'll link to the glossary. This should help make it less intimidating to
first-time readers as well as generally make it easier to follow the sentence.
PS: It's likely easier to review this PR in "rich diff" mode, since I've had to re-wrap the entire passage.
> Tweak opening "important note" in installing-packages tutorial

- source/tutorials/packaging-projects.rst
Small grammatical update to the docs.
> Grammatically updated the docs

- source/tutorials/packaging-projects.rst
This is an attempt to modernize the suggestions in the packaging tutorial. Changes:
* Include `pyproject.toml`
* Use `pypa/build` for building the SDist & wheel, drop the `--user` recommendation (no longer needed and often harmful)
* Update links to poetry
I've also rewrapped a few lines without changes that were ridiculously longer than 80 characters for consistency.
Closes #809.
> chore: use modern package setup for example

- .github/workflows/test.yml
- .travis.yml
Travis CI has a new pricing model which places limits on open source.
* https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
* https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
Travis support has also become unresponsive to developers who have run out of free credits, and many projects are moving to GitHub Actions instead. 
And https://github.com/pypa builds can not longer build:
> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.
> Owner pypa does not have enough credits.
---
This GHA config does much the same as the deleted Travis one. Two differences: tests with current …
> Replace Travis CI with GitHub Actions

- requirements.txt
- source/conf.py
- source/index.rst
- source/tutorials/packaging-projects.rst
Followup to #817, related to #809.
---
I've split out the setup.cfg changes. I still would highly recommend setup.cfg, because:
* It is a static, easily parsable file, which is highly superior to a Python file - for example, cibuildwheel should soon gain support for reading the Requires-Python metadata from the PEP 621 location or from setup.cfg, but setup.py is impossible to reliably parse.
* It avoids many common issues, like opening files without with, encoding issues, and issues with accessing the version.
* It keeps setup.py as _just_ logic, making it clear what's "dynamic" and what's just regular metadata.
* It's actually readable, much less boilerplate
* Less chance of importing from distutils before setuptools
* The PyPA projects, like twine, build, etc, use setup.cfg.
* It's been …
> chore: use setup.cfg as main config file

- source/tutorials/packaging-projects.rst
Closes pypa/packaging-problems#436
I've reordered the fields to match the description order, and synced the description orders for the two tabs. (I think I matched the order that is given in the setuptools docs originally for the cfg lines). I also added a missing description for `python_requires` to both tabs.
Personally, I rather think `python_requires` should have been metadata, not options, since it fills the Requires-Python slot, but it is in options.
> fix: add a few missing parts to setup.cfg setup

- source/tutorials/packaging-projects.rst
Based on recent issues, this rewording hopefully will reduce a seemly common
error of adding a completely empty setup.py file. Closes pypa/packaging-problems#446
> fix: reduce the chance of a user having an empty setup.py file

- source/specifications/platform-compatibility-tags.rst
PEP600 now supersedes all previous PEPs to define a future-proof manylinux standard.
> Mention manylinux_x_y in platform tags specification

- source/guides/distributing-packages-using-setuptools.rst
Fixing a typo in the documentation
> Fix a typo

- source/guides/distributing-packages-using-setuptools.rst
The developer's guide for setuptools has been updated. See pypa/setuptools#2456
> Update link to setuptools doc

- source/tutorials/packaging-projects.rst
In https://github.com/pypa/packaging.python.org/pull/823, it was mentioned that `project_urls` might be a good thing to show. This adds that example.
Happy to change this as needed, or if it's seen as "too much", that's fine too, it's just a followup to https://github.com/pypa/packaging.python.org/pull/823#discussion_r571482624 as promised in https://github.com/pypa/packaging.python.org/pull/823#discussion_r571484257 . I don't think I've used it in setup.py, I think I got the setup.py version right...
> feat: add project_urls example

- source/tutorials/packaging-projects.rst
~~Update sample setup.py to correctly load README.md when cwd is not the same directory that setup.py lives in (discussed in #696). The updated README-loading code is for Python 3+. Since Python 2 has been deprecated, it is probably safe to assume that anyone reading this guide is most likely using Python 3.~~ The guide has been updated significantly since the inception of this PR, which obviates the `setup.py` changes. Also see https://github.com/pypa/packaging.python.org/pull/711#issuecomment-783835643
Also explain why README.md should be added to the package (discussed in #696).
> Explain why README.md should be added to sdist

- source/specifications/binary-distribution-format.rst
A [small change to the wheel spec](https://discuss.python.org/t/escaping-versions-for-wheel-sdist-and-dist-info-names/5605/8) is likely to better represent version numbers in wheel filenames. @pfmoore suggested that the wheel spec should be moved here as part of that.
For now, I have copied the contents of PEP 427 to here with no changes, to simplify review.
> Move wheel spec into packaging.python.org specifications section

- source/specifications/binary-distribution-format.rst
From the discussion at https://discuss.python.org/t/escaping-versions-for-wheel-sdist-and-dist-info-names/5605
These are the same rules as for .dist-info directories, specified in [recording installed packages](https://packaging.python.org/specifications/recording-installed-packages/), but with a bit more description for names.
> Wheel spec: Update rules on escaping components of wheel filename

- source/specifications/binary-distribution-format.rst
Changes as suggested by @pfmoore on #844.
> Clarify filename rules in wheel spec

- source/guides/distributing-packages-using-setuptools.rst
As discussed in the discuss.python topic ["Use of “less-than next-major-version” (e.g., `<4`) in `python_requires` (setup.py)"](https://discuss.python.org/t/use-of-less-than-next-major-version-e-g-4-in-python-requires-setup-py/1066) and other places there can be some side effects of adding `<4` to a library's `python_requires`. This PR removes it, as requested by @njsmith in the discuss.python topic.
The section above the lines discussed in the topic that uses compatible release syntax is also removed given that `~=3.3` also enforces `<4`.
My apologies in advance if this was already discussed in an Issue and decided against (I didn't see any when I scrolled through) or in a previously closed PR. Please let me know if you'd like me to open an Issue to discuss this PR topic instead.
Tagging …
> fix: Remove '<4' from python_requires in packaging guide

- source/specifications/core-metadata.rst
Following [this discussion on discourse](https://discuss.python.org/t/core-metadata-email-fields-unicode/7421). The file format of core metadata is not precisely defined (PEP 241 said RFC 822, but that's outdated in practice), but there is a practical standard: the major tools consuming metadata use the `email.parser` module with the (default) `compat32` policy. I think it's better to describe the situation than to leave it completely unspecified.
Hopefully this is an interim measure until someone gets around to describing the format properly. But that's a much bigger job, and so far no-one is volunteering.
> Describe the file format of core metadata

- source/tutorials/packaging-projects.rst
> Fix a typo in `packaging-projects.rst` under `Creating pyproject.toml`

- source/tutorials/packaging-projects.rst
Closes #838. This should make a common user mistake harder.
I do think this should produce a better error message, though, when `setup.py` does not contain a call to `setuptools.setup()`. Possibly via a change to setuptools or pip?
> fix: try harder to avoid a common user mistake

- source/guides/dropping-older-python-versions.rst
> Update "Dropping old Python" with `universal=0`

- source/tutorials/packaging-projects.rst
Resolves #847
This PR adopts the use of a `src` directory for the "Packaging Python Projects" tutorial. In addition to the use of `src` it introduces `package_dir` and where to look for packages with `[options.packages.find]` in `setup.cfg` or the `where` arg for `setuptools.find_packages` in `setup.py`.
The added documentation adopts the use of the term "root package" from [the old Distutils Examples docs](https://docs.python.org/3/distutils/examples.html#pure-python-distribution-by-package), but there may be more preferred terminology for this and I'm happy to revise this as desired.
Tagging @di as he transferred Issue #847 from pypa/sampleproject.
> fix: Use src directory structure for packaging tutorial

- source/tutorials/packaging-projects.rst
This PR is a follow up to PR #859 to apply suggested revisions and formatting (cc @webknjaz).
* Adds directory trailing slashes to indicate dir structure for clarity, so abandons `tree` behavior for `ls -F` behavior :+1: 
* Revise phrasing for `package_dir` description: "collection" -> "mapping"
* Attempts to clarify the definition of "root package"
In PR #859 it was also [suggested that](https://github.com/pypa/packaging.python.org/pull/859/files#r592172904)
> An empty package name represents the "root package", so in this case the root package is in the ``src`` directory.
might get rephrased to "flat", but the links provided to the discussion at the PyCon 2019 - PyPA Sprints + Summit notes seem to indicate that this is referring to terminology related to a **non**-src directory …
> fix: Apply formatting corrections for packaging tutorial

- noxfile.py
In nitpicky mode, Sphinx will error out on the first warning met. This change makes it collect all the warnings before returning with an error.
> Add `--keep-going` to the Sphinx invocation

- source/discussions/pip-vs-easy-install.rst
Resolves #830 
Note in the ["pip vs easy_install" discussions](https://packaging.python.org/discussions/pip-vs-easy-install/) that `easy_install` is deprecated. Additionally add a link to the [release notes for `setuptools` `v42.0.0`](https://setuptools.readthedocs.io/en/latest/history.html#v42-0-0) in which in the Breaking Changes it is noted that
> Mark the easy_install script and setuptools command as deprecated
cc @qsqa for comments as they opened up the Issue. Also tagging @webknjaz as they requested a PR from the Issue.
RTD build of the page in question: https://python-packaging-user-guide--872.org.readthedocs.build/discussions/pip-vs-easy-install/
> fix: Note that easy_install is deprecated

- source/guides/single-sourcing-package-version.rst
This changes a try/except to a version check. Not only is this statically typable in MyPy, but it literally states exactly what the comment below states, but in code. :)
> fix: use sys.version_info over try/except

- source/conf.py
- source/guides/creating-and-discovering-plugins.rst
- source/specifications/entry-points.rst
Closes #870. I think this was the outcome of the discussion?
> chore: update to using importlib.metadata for entry_points

- source/conf.py
- source/guides/creating-and-discovering-plugins.rst
- Show how a module would be loaded. A dictionary of modules will not be loaded, unless created by the user. The example code was corrected.
- Update links to external documentation
- Hint that specifying entry points is not limited to setuptools. For  example [flit](https://flit.readthedocs.io/en/latest/pyproject_toml.html#entry-points-sections)  and [poetry](https://python-poetry.org/docs/pyproject/#plugins) support it too.
Following up on #870 and #879
> Fix description of entry points mechanism

- source/tutorials/packaging-projects.rst
Towards #866. This seemed to be the more common style, and reads better in my opinion, even though it does add extra syntax.
> Packaging Python Projects: Normalize terms to lowercase

- source/tutorials/packaging-projects.rst
Towards #866.
I removed the comments and the example name, because I felt that there was sufficient guidance in this section (including in the attribute list below the file sample).
> Packaging Python Projects: Tweak package naming suggestions

- source/guides/distributing-packages-using-setuptools.rst
This updates the build prodedure for modern best practices, using `pypa/build`. (Delayed) fix for an issue somewhere where it was pointed out this page was old, but forget where it was. Will dig around a bit for it tomorrow.
The page still needs the updates requested in #887; this page seems quite old.
> Use a PEP517 build front-end in the setuptools guide

- source/guides/distributing-packages-using-setuptools.rst
- source/guides/dropping-older-python-versions.rst
> Reduce Python 2 Universal wheels discussion

- source/tutorials/packaging-projects.rst
Towards #866 and #887.
I'm still inclined to encourage using a virtual environment for the whole thing, instead of `pip install --user`, but that feels like a separate PR.
> Packaging Python Projects: Remove references to editable installs

- source/tutorials/installing-packages.rst
- source/tutorials/packaging-projects.rst
Towards #866.
This is mostly adding more links glossary entries, with a couple more substantial changes that felt related.
> Packaging Python Projects: Add/update links to other docs

- source/key_projects.rst
Fixes #915.
I'm not sure about the non-`#pypa` channels. Maybe we can get the maintainers of those projects to comment on their preferred communication channels (or just remove the IRC links, and rely on projects' docs).
> Change IRC links to Libera.Chat

- source/tutorials/packaging-projects.rst
Closes #866 
Rather than isolating it to the `python -m build` step, my hope is that this lets readers know then can get help at any point along the way. I thought about adding internal links to the `.. note` to the various steps, or adding specific `?title=` links, but I also thought that might be unnecessarily noisy.
*Sorry for the duplicate of #921 ; I renamed the branch in the GitHub UI, thinking it might carry over into the PR.*
> Packaging Python Projects: Make packaging-problems link more prominent

- source/key_projects.rst
After scanning through some of the projects, it seemed like most of the links to IRC and mailing lists are not reliable ways of engaging with a project. Rather than direct users to those, I thought it might be better to rely on each project's repo and documentation to point users in the right direction.
> Prune project links

- source/key_projects.rst
This adds multibuild, pre-req for #910. CC @matthew-brett - better description welcome (we don't have much of a description on cibuildwheel either, @pypa/cibuildwheel-team).
> chore: add multibuild

- source/guides/installing-stand-alone-command-line-tools.rst
- source/key_projects.rst
This updates for the new location of pipx.
> chore: move pipx to pypa

- source/guides/packaging-binary-extensions.rst
This adds a mention of pypa's cibuildwheel and multibuild here before going into the (highly outdated, currently) specifics of building wheels. For most users, this likely is the correct place to go, rather than trying to set things up themselves. For those who might want to do things themselves, the following sections still need updating.
> binary-extensions: add cibuildwheel and multibuild

- source/guides/installing-using-pip-and-virtual-environments.rst
Fixes #783.
This patch also completes the "tabification" this document.
> Fix executable dir in + tabify pip & virtual envs guide

- source/guides/packaging-binary-extensions.rst
Adding a mention of pybind11, which is quite popular (used by SciPy, PyTorch, and many, many others).
Disclaimer: I'm a pybind11 maintainer now.
> binary-extensions: add pybind11

- requirements.txt
Things look fine after rebuilding.
> Update the version of Sphinx to 4.0.3

- locales/messages.pot
- source/guides/distributing-packages-using-setuptools.rst
- source/guides/dropping-older-python-versions.rst
- source/guides/hosting-your-own-index.rst
- source/guides/installing-using-pip-and-virtual-environments.rst
- source/guides/making-a-pypi-friendly-readme.rst
- source/guides/using-testpypi.rst
- source/tutorials/creating-documentation.rst
- source/tutorials/installing-packages.rst
- source/tutorials/managing-dependencies.rst
- source/tutorials/packaging-projects.rst
> Change to `code-block:: text` from `code-block:: bash` & update the version of pip

- source/guides/packaging-binary-extensions.rst
About a month ago Microsoft permanently killed off https://www.microsoft.com/en-gb/download/details.aspx?id=8279 (MSVC 2008 for Python 2.7); it was officially at end-of-really-extended-life-for-python-2.7 since 2018. I don't think details about Python 3.4 are all that interesting to anyone anymore, either.
Included the caveat discovered by matplotlib for MSVC 2019.
> binary-extensions: update Windows instructions

- source/guides/distributing-packages-using-setuptools.rst
This PR apply the following changes in `source/guides/distributing-packages-using-setuptools.rst`:
- Make `setup()` arg names literal (e.g. `name`, `version`, `description`), so that translators know it should not be translated.
- Fix a paragraph that had full-stop character before an "and", and remove literal from placeholder pair that ought to be translated.
> Improve distributing packages

- source/key_projects.rst
No update since 7 years. I think "less is more", and removed it from the list.
> bento has seen to update since 2014.

- source/guides/using-testpypi.rst
Some small tweaks after reading the guide (prompted by https://github.com/pypa/packaging.python.org/issues/479#issuecomment-900738843).
> Copy-edit TestPyPI guide

- source/tutorials/packaging-projects.rst
Very tiny typo correction.
Incorrect: "tutoral"
Correct: "tutorial"
> Fix typo ("tutoral" -> "tutorial")

- source/guides/making-a-pypi-friendly-readme.rst
Use simpler pathlib example instead of `os.path`.
> Switch example reading Markdown to use pathlib

- noxfile.py
- source/conf.py
I was playing with building the localized sites on RTD and noticed that the `*.po` files are not being picked up. So I dug deeper and now realized that Sphinx looks for the `locales/` dir relative to `conf.py` and fixed that.
Additionally, since there was no way to invoke `nox` locally for building the docs in other languages, I've adjusted the nox file to bypass any posargs to the underlying invocation of `sphinx-build` and now it's possible to do this. For example:
```console
$ python -m nox -s build -- -D language=uk
nox > Running session build
nox > Creating virtual environment (virtualenv) using python3 in .nox/build
nox > python -m pip install -r requirements.txt
nox > sphinx-build --color --keep-going -j auto -b html -n -W -D language=uk source build
Running Sphinx v4.0.3
loading …
```
> Adjust nox config for building the translated site versions

- source/specifications/direct-url.rst
Found this issue when fixing broken links.
> direct-url: Wrap `pip` commands with backticks

- source/guides/using-manifest-in.rst
I recently found out the hard way that, if you have a file `src/foobar/stuff.txt` in your project, writing just `include stuff.txt` in your `MANIFEST.in` won't do anything; you need to write `include src/foobar/stuff.txt` instead.  This PR tries to make that clearer to readers.
> Clarify how MANIFEST.in's "include" and "exclude" work

- source/guides/distributing-packages-using-setuptools.rst
If pypa/sampleproject#155 gets merged, the link may get broken, and also may cause a confussion. So, this PR removes the only reference to that file, and also explained why.
> Remove the sample project MANIFEST.in reference

- requirements.txt
Errors: https://github.com/pypa/packaging.python.org/runs/4420714180?check_suite_focus=true#step:8:12
Sphinx 4.3.1 should fix these errors.
@webknjaz
> Use Sphinx 4.3.1

- source/key_projects.rst
Recent move in to the PyPA requires a few changes here. :)
Will try to work on updates to the tutorials at some point to get a Flit PEP 621 version in. Should it be a new page, or should we try to integrate it into the current tutorial?
> Move Flit into PyPA

- source/guides/distributing-packages-using-setuptools.rst
- source/tutorials/packaging-projects.rst
Closes #667. Continuation of #672, closes #672.
I tried to respect the original spirit of #672, even if that meant _not_ updating the rest of the page (i.e. noting the deprecation of direct `setup.py` invokations and encouragement for `pyproject.toml` for static metadata), as this would require a bit more work. I prefer to defer that to a future PR.
> Advise against using distutils directly, take 2

- source/contribute.rst
At the moment the documentation doesn't run on Python 3.6 because sphinx-inline-tabs is incompatible to it, so I upgraded Python to a more recent version. I was still a bit conservative, so happy to bring it up to 3.9 :) not sure if all the dependencies run on 3.10 already.
> Upgrade expected Python version

- source/specifications/binary-distribution-format.rst
This should wait on the resolution of [this Discourse thread](https://discuss.python.org/t/revisiting-distribution-name-normalization/12348) about normalisation rules. I'm presuming it will come out in favour of keeping PEP 503 normalisation for wheel filenames.
This was an oversight on my part - I wanted the spec to directly describe the normalisation rule, not only refer to another spec, because I think this is clearer for people reading it. But I missed out the lower-casing step from PEP 503 in my description. The specs [for `.dist-info`](https://packaging.python.org/en/latest/specifications/recording-installed-packages/) and [for sdists](https://packaging.python.org/en/latest/specifications/source-distribution-format/) both refer to PEP 503 without trying to copy the relevant details, …
> Say that distribution names should be lowercase in wheel filenames

- source/tutorials/managing-dependencies.rst
We could also add https://github.com/FFY00/trampolim, but I wanted to see what you think first (and if we add more, all descriptions should probably be made either as comparisons to pipenv, or as pipenv-unrelated descriptions).
I believe these alternatives deserve an entry on this page :slightly_smiling_face:
> Add PDM to the list of alternatives to Pipenv

- source/specifications/core-metadata.rst
See https://discuss.python.org/t/python-metadata-format-specification-and-implementation/7550/25
> Require metadata to be serialised using UTF-8

- source/guides/distributing-packages-using-setuptools.rst
Fixes https://github.com/pypa/packaging.python.org/issues/643.
Same wording as https://github.com/pypa/warehouse/pull/10872.
Preview: https://python-packaging-user-guide--1056.org.readthedocs.build/en/1056/guides/distributing-packages-using-setuptools/#classifiers
> Document the 'Private ::' classifier prefix

- source/guides/tool-recommendations.rst
This is a more detailed recommendation that breaks up the recommendation
into multiple parts, to reflect that multiple tools need to be used in
workflows today to maximise compatibility with existing platforms.
It also recommends that deployed applications be isolated from the
system packages, as was implied but not explicitly noted.
The move away from Pipenv as the primary recommendation is a reflection
of the change that application development workflows have a greater
diversity in mature tooling available for them.
Toward #912
> Update the "Application dependency management" recommendations

- source/tutorials/packaging-projects.rst
`"wheel"` is included with proper version by `get_requires_for_build_wheel` from PEP 517, and isn't required for making an sdist, and might not be required in the future at all (in which case setuptools will modify `get_requires_for_build_wheel`). [It's available even in 40.8](https://github.com/pypa/setuptools/blob/c1243e96f05d3b13392a792144c97d9471581550/setuptools/build_meta.py#L130).
This was probably my fault (actually, yes it was, git blame's to me). It is very common, so maybe we should mention wheel is not required? I'd go for simple, I think, but it's possible someone will try to add it again in a PR.
> No longer suggest `wheel` in build-requires for PEP 517 builds

- source/guides/tool-recommendations.rst
Not all projects that need to be installed are applications. Libraries
should also fall into this recommendation, of what installer tools
should be used when working on them.
Closes https://github.com/pypa/packaging.python.org/issues/865
> Change "application" to "project" in installer recommendation

- source/specifications/binary-distribution-format.rst
This is a typo according to https://github.com/pypa/pip/issues/9616#issuecomment-780699010
See also https://github.com/python/peps/pull/2523
> In wheel spec, 'include' should be 'headers'

- source/conf.py
- source/tutorials/packaging-projects.rst
This is a simpler, PEP 621 _only_ version of #1030. Might not be ready to go this route, but this would be what I think we could do.
Also, I'd love to move this over to using pipx. That would really simplify the ending commands (building and publishing), and would remove the unix/windows split from everything except the first line, where pipx would be installed.
_Update from @bhrutledge_:
Merging is currently blocked on changing the example package name to support backend discovery; see discussion in https://github.com/pypa/packaging.python.org/pull/1031#discussion_r891096802. Until that's fixed, the tutorial is broken. Further content improvements can be made in future PRs. Closes #1085.
> feat: add PEP 621 config only

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
A bit of maintenance on the [Publishing package distribution releases using GitHub Actions CI/CD workflows](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) guide:
- Update the host OS to ubuntu-latest
- Update the actions/setup-python to v3
- Use Python 3.10
> GHA publish to TestPyPI guide: Update actions, environment and Python

- source/tutorials/packaging-projects.rst
Set and document `license.file` in project metadata in the packaging tutorial
Fixes #1097
> Declare license file in packaging tutorial

- source/flow.rst
- source/index.rst
Per @pfmoore 's suggestion here:
https://discuss.python.org/t/adding-a-packaging-flow-overview-to-the-pypa-docs/15060/3?u=cameron
this pull request offers a document providing a conceptual overview of the PyPA package publishing flow, proposal here:
https://discuss.python.org/t/adding-a-packaging-flow-overview-to-the-pypa-docs/15060
I came to write this after writing this post: https://discuss.python.org/t/modernising-my-packages-am-i-thinking-about-this-all-wrong/14558?u=cameron where I described the problems I had trying to figure out how to move to a more modern `pyproject.toml` based system for my packages, largely because I became swamped in a sea of detailed documents which I could not string together; the PEPs in particular are written for people _already_ very familiar with the …
> adding a "packaging flow" overview document

- requirements.txt
- source/_static/overrides.css
- source/conf.py
While working on #1116, I found that sphinx-copybutton has a [new release](https://github.com/executablebooks/sphinx-copybutton/blob/master/CHANGELOG.md) that changes the design, and fixes the alignment issue that previously required an [override to fix](https://github.com/pypa/packaging.python.org/pull/946/files#diff-895eee78fb3b0dce9e6556417305d5867a787b35a7ce996bd351e6ccbe8839f7).
> Upgrade copybutton

- requirements.txt
- source/tutorials/packaging-projects.rst
On at least Chrome and Safari on macOS, the rendering of directory trees are hard to read:
Noting that the [`pypa_theme`](https://github.com/pypa/pypa-docs-theme) inherits from [`python_docs_theme`](https://github.com/python/python-docs-theme), I poked around on the Python docs and discovered that [it's not an issue there](https://docs.python.org/3/library/__main__.html#main-py-in-python-packages). That led me to https://github.com/python/python-docs-theme/pull/87, which was released in 2021.11.1. Sure enough, upgrading fixes the output:
This also includes "Make sidebar scrollable and sticky (on modern browsers)", which I think is a nice enhancement.
> Use latest python-docs-theme

- source/guides/analyzing-pypi-package-downloads.rst
Noticed the existing link points to an archived repo, updates the link to point to the replacement.
> update the linehaul link to point to https://github.com/pypa/linehaul-cloud-function/

- requirements.txt
This is quick fix to address broken `:rfc:` links, which seem to have been addressed in [4.4.0](https://www.sphinx-doc.org/en/master/changes.html#release-4-4-0-released-jan-17-2022).
Not upgrading to 5.x because that should include investigation of possible breaking changes.
> Upgrade to Sphinx 4.5.0

- source/key_projects.rst
Pipenv is currently actively maintained by @matteius and
myself (@oz123). The project has seen multiple releases
this year, and many bugs fixed.
The activity on the project has even attracted new contributions.
Additionally, the project is actively backed by the Python foundation
and tidelift.
> Update status of Pipenv - is actively maintained

- source/key_projects.rst
source/key_projects.rst
this was pointing to `bugs.python.org`
links for ensurepip and distutils issues remain unmodified
> venv issues link

- source/guides/making-a-pypi-friendly-readme.rst
I noticed that the link was taking the reader to the main index page.
Change the links to be more specific to target the actual pages in question.
Signed-off-by: Mike Fiedler <miketheman@gmail.com>
> docs: update references to specific pages

- noxfile.py
This improves the ergonomics and help text of nox slightly.
Here's the new help text:
```
Sessions defined in /Users/henryschreiner/git/webpages/packaging.python.org/noxfile.py:
- translation -> Build the gettext .pot files.
- build -> Make the website.
- preview -> Make and preview the website.
- linkcheck -> Check for broken links.
sessions marked with * are selected, sessions marked with - are skipped.
```
Also, now if you just type `nox`, instead of trying to build twice, and
previewing, then link checking, it will just produce the above help text.
Also removed `py="3"` since it doesn't really do anything anymore.
> chore: nicer nox help text

- source/tutorials/installing-packages.rst
Per more recent PEPs (e.g. 621), extras may be produced by build tools
other than setuptools if the packager isn't using setuptools as the
build system. In this document, which is mostly about installing,
it seems simpler then to avoid mentioning that setuptools defines
the extras and to simply show the user how to do the install without
mentioning what tool is involved in defining them.
The main motivation for doing this (besides that I think it's indeed slightly simpler) was I want a page to intersphinx link to from my install documentation (telling users to install an extra), but I indeed don't use setuptools, and don't want to confuse users. It may be there's a better place for me to link to (in which case lemme know :) but figured I'd propose the change no matter what.
> Divorce the section on pip installing extras from setuptools

- source/tutorials/packaging-projects.rst
See [my comment](https://github.com/pypa/packaging.python.org/pull/1143#issuecomment-1251022855) on documenting how to include the license in the distribution
> Document backend license inclusion behaviour

- source/tutorials/packaging-projects.rst
Reverts pypa/packaging.python.org#1098
While investigating https://github.com/pypa/twine/issues/926, I discovered that using `license = { file="LICENSE" }` will result in the contents of `LICENSE` being displayed on PyPI in the "Meta" sidebar section. For example, see:
https://test.pypi.org/project/example-package-bhrutledge/0.0.1/
When I remove that line, I get what I think is the desired behavior, which is the name of the license:
https://test.pypi.org/project/example-package-bhrutledge/0.0.2rc1/
FYI @EpicWink
> Revert "Declare license file in packaging tutorial"

- source/discussions/index.rst
- source/discussions/src-layout-vs-flat-layout.rst
x-ref #320 
This discussion covers the main topics discussed in #320, trimming the opinions/preferences stated there and keeping things limited to the behaviour differences between the two formats. I've followed the same style as pip vs easy_install or wheel vs egg pages here.
> Add initial draft of src vs flat layout discussion

- source/key_projects.rst
distlib has been migrated from BitBucket to GitHub. update the links accordingly
> update distlib links

- .github/workflows/test.yml
- .github/workflows/translation.yml
Some of them like setup-python before v4 used node.js 12, which is deprecated (see [annotations in actions log](https://github.com/pypa/packaging.python.org/actions/runs/3306153606)).
> Update versions of github actions

- source/guides/distributing-packages-using-setuptools.rst
This is a quick hack to resolve the `linkcheck` failure in CI, which is blocking merging of other PR's. Switching this document to use `pyproject.toml` is a larger undertaking than I can take on right now.
Also, as noted elsewhere, this doc needs some attention.
https://github.com/pypa/packaging.python.org/issues/887
https://github.com/pypa/packaging.python.org/issues/792
> Fix broken links to setup.py and .cfg

- source/specifications/core-metadata.rst
- source/specifications/declaring-project-metadata.rst
Switched from using the term "field" to "key" to align with TOML terminology. Also updated a reference for `dynamic`.
Closes #1101
> Add an example and list of keys to the project metadata spec

- source/guides/creating-and-discovering-plugins.rst
Since #1031 is merged, let’s gradually move away from a setuptools centric view.
> Add PEP 621 tab for entry points docs

- source/glossary.rst
There's an extra backtick that's not needed in the glossary entry for "egg"
Rendered at: https://packaging.python.org/en/latest/glossary/
> Doc: remove extra backtick in Glossary

- source/guides/single-sourcing-package-version.rst
On the `Single-sourcing the package version` page, the newer `pyproject.toml` is not mentioned for setuptools. This adds a clean way of configuring it in `pyproject.toml`.
> Single-sourcing the package version: Add instructions for setuptools using pyproject.toml

- source/specifications/dependency-specifiers.rst
This moves PEP 508 to packaging.python.org as discussed on discord
Diff between [PEP 508](https://github.com/python/peps/blob/1a87312fb30f86e7690c033574e5f6a2767035f9/pep-0508.txt) and dependency-specifiers.rst: https://gist.github.com/konstin/059c0e72ff77049e0eb2ce0d738990fd. I've removed the PEP-specific paragraphs, added an introductory sentence and s/this PEP/this document/g.
> Add specification for dependency specifiers

- source/guides/installing-scientific-packages.rst
Listed as "Archived" at https://www.cgohlke.com/.
> Remove defunct list of Windows installers.

- source/tutorials/packaging-projects.rst
Version 3.4 added PEP 660 support
Version 3.3 added PEP 621 support
https://flit.pypa.io/en/stable/history.html
Feels wrong to allow a version here that doesn't support those
> Update the flit_core lower bound

- source/specifications/direct-url.rst
Add the hashes key to the Direct URL data structure, as a approved at https://discuss.python.org/t/draft-pep-amendment-to-the-pep-610-direct-url-json-data-structure/22299/4.
@pfmoore
> Add a hashes key to the direct URL data structure

- requirements.txt
- source/guides/distributing-packages-using-setuptools.rst
- source/guides/installing-using-pip-and-virtual-environments.rst
- source/specifications/direct-url.rst
- source/tutorials/installing-packages.rst
Use 'req @ url' syntax when using pip to install from a remote git repository over 'url#egg=req' to avoid the use of #egg= fragments with a non-PEP 508 name. This will be required in pip v25.0+.
- c.f. pypa/pip#11617 for more details.
> Use `req @ url` syntax to install from remote VCS

- source/specifications/direct-url.rst
* Use the correct syntax for [url fragments with `pip`](https://pip.pypa.io/en/stable/topics/vcs-support/#url-fragments) of the form
```
python -m pip install "pkg @ vcs+protocol://repo_url/#subdirectory=pkg_dir"
```
* Revises PR #1207
> fix: Use proper subdirectory syntax for pip url fragments

- source/specifications/direct-url.rst
- source/specifications/entry-points.rst
- source/specifications/externally-managed-environments.rst
- source/specifications/index.rst
- source/specifications/recording-installed-packages.rst
- source/specifications/virtual-environments.rst
Closes #1210 
Closes #1211 
Closes #1212
> Clarify specs for external installer interactions

- source/specifications/platform-compatibility-tags.rst
Also update to say spaces are not allowed in wheel tags (see https://github.com/pypa/packaging/issues/652 ).
> Move PEP 425 over

- source/tutorials/installing-packages.rst
The wiki updated the `python3 --version` command but forgot to update the error msg.
This diff updates the error msg.
> Fix: python -> pyton3 to match the python3 --version's not found error

- source/guides/analyzing-pypi-package-downloads.rst
The CI linkcheck is failing: for example https://github.com/pypa/packaging.python.org/actions/runs/4405998144/jobs/7717630748 in https://github.com/pypa/packaging.python.org/pull/1092.
Because `https://github.com/ofek/pypinfo/blob/master/README.rst` was converted to `https://github.com/ofek/pypinfo/blob/master/README.md` yesterday.
https://github.com/ofek/pypinfo/pull/146
> Fix linkcheck

- source/tutorials/packaging-projects.rst
Updated to the new name (avoiding mentioning a PEP) of pdm-backend.
CC @frostming.
> chore: update name of PDM backend

- source/guides/installing-using-pip-and-virtual-environments.rst
- source/tutorials/installing-packages.rst
Resolves #1209
Shells like `zsh` have glob qualifiers that will error if an extra is not quoted. While the glob qualifiers can be disabled, adding quotes guards against errors if people are copy-pasting or do not know that they can disable the behavior.
> Quote extras to guard shells with glob qualifiers

- source/guides/installing-using-pip-and-virtual-environments.rst
As pointed out by @henryiii in https://github.com/pypa/packaging.python.org/pull/1216#pullrequestreview-1342428923, adding quotes to version information on packages provides safeguards against common mistakes. Additionally this matches style with https://github.com/pypa/pip/pull/11842.
> Quote guard version requirements for pip installs

- source/specifications/direct-url-data-structure.rst
- source/specifications/direct-url.rst
- source/specifications/index.rst
This is the second part of #1198.
The Direct URL data structure, currently embedded in the specification of the `direct_url.json` metadata, is proving useful is other contexts.
In particular pip uses it:
- in the installation report, to report where artifacts where downloaded from, whether they have been specified as a name+version or as a direct URL
- in the pip inspect format (the original PEP 610 scope, additionally emulated for legacy editable installs)
- to record the the download origin of entries in the cache of locally built wheels
To make easier for tools (and possibly future interoperability standards) to reference the data structure specification in various contexts, this PR extracts it into a standalone document.
This does not materially change the original spec.
This PR has …
> Extract the Direct URL data structure into a standalone document

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
repository_url is deprecated, use repository-url instead , per https://github.com/pypa/gh-action-pypi-publish/blob/a3a3bafbb3e5a75a854ae1bc53ae128cf22c4af4/action.yml#L15
> repository_url is deprecated, use repository-url

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
This updates the GHA guide a bit with non-controversial changes (hopefully). I think using pipx instead of the current setup would be simpler and is better practice, I might do that in a followup.
Changes:
* Point out this works only for pure Python, link to cibuildwheel for binary packages
* Use Python 3.x
* Drop mention about needed pyproject.toml to use build and links to PEPs (it is backward compatible if it's missing)
* Use more recent versions of actions and the tagged versions of all actions
> chore: update GHA guide

- source/specifications/declaring-project-metadata.rst
E.g. the contents of `README.md` if referred to by `readme` is expected to not change unless the `readme` field itself is marked as `dynamic`.
> Clarify that static metadata include external data that is referenced

- source/specifications/index.rst
GitHub: fixes https://github.com/pypa/packaging.python.org/issues/1238
> Fix link to specifications page on `pypa.io`

- source/guides/installing-using-linux-tools.rst
Due to an expired security certificate: https://github.com/sclorg/softwarecollections/issues/123
I think this is a temporary swap; if that issue gets resolved, I'll change it back.
> Fix broken Software Collections link

- source/guides/installing-stand-alone-command-line-tools.rst
- source/tutorials/creating-documentation.rst
Replaced the pip `-U` option with `--upgrade` to clarify the difference to `--user`. Also fixed some `pipx` output.
> Clarified pip `--upgrade` option and fixed output

- .readthedocs.yaml
- source/overview.rst
The bottle project page is not reachable at the moment, so I have replaced the link temporarily with a reference to PyPi.
I'll open a ticket soon.
> Replace link to bottle project page with PyPi link

- .github/workflows/test.yml
The test workflow triggers on a daily cron:
```yml
on: 
push:
pull_request:
schedule:
- cron: "0 6 * * *" # daily at 6am
```
This is good for upstream, but not necessary for contributors' forks, as it sends a daily email to contributors when it fails:
https://github.com/hugovk/packaging.python.org/actions
Let's add a condition so the `schedule` trigger only runs for upstream, and all other triggers run for both upstream and forks.
> CI: Don't run cron for forks

- source/discussions/wheel-vs-egg.rst
- source/glossary.rst
- source/specifications/binary-distribution-format.rst
- source/specifications/platform-compatibility-tags.rst
PEP 427 is about the binary distribution format *wheel*. The full standard specification is available in the guide so we should link to it instead of the PEP. The PEP is rather a historical document, PEPs are part of the process, they are not the specification document.
Preview:
* https://python-packaging-user-guide--1229.org.readthedocs.build/en/1229/
* and more specifically:
* https://python-packaging-user-guide--1229.org.readthedocs.build/en/1229/discussions/wheel-vs-egg/
* https://python-packaging-user-guide--1229.org.readthedocs.build/en/1229/glossary/#term-Wheel
* https://python-packaging-user-guide--1229.org.readthedocs.build/en/1229/specifications/platform-compatibility-tags/#faq
See also: https://github.com/pypa/packaging.python.org/pull/1213
> Fix or replace references to PEP 427

- source/specifications/declaring-project-metadata.rst
I'm not sure whether this is controversial or not.
In pretty much all other places, the project URLs mapping keys are capitalized, including the "setuptools" guide page. Update `pyproject.toml` examples too for consistency and current practices.
Examples:
* packaging.python.org setuptools guide: https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls
* PyPA's own `packaging` package: https://github.com/pypa/packaging/blob/main/pyproject.toml#L32-L34C6
* Poetry documentation: https://python-poetry.org/docs/pyproject/#urls
* Flit documentation: https://flit.pypa.io/en/latest/pyproject_toml.html#urls-table
* core-metadata spec: https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-project-url
If the keys are not …
> Project URLs keys should be capitalized in pyproject.toml

- source/guides/creating-and-discovering-plugins.rst
- source/guides/hosting-your-own-index.rst
- source/tutorials/installing-packages.rst
Preview: https://python-packaging-user-guide--1213.org.readthedocs.build/en/1213/
> Replace refs to PEP-503 with simple repository API

- source/specifications/binary-distribution-format.rst
Follow-up from discussion here: https://discuss.python.org/t/guidance-on-wheel-build-numbers-for-external-reference-security-fixes/29621
> Add warning about reference interop for build numbers

- source/specifications/source-distribution-format.rst
[PEP 721](https://peps.python.org/pep-0721/) was [accepted](https://discuss.python.org/t/23903/10).
Its Specification section was written to be simply copied here, so, here it is!
I've also added a History section to help #1203.
> PEP 721 — Using `tarfile.data_filter` for source distribution extraction

- source/specifications/direct-url-data-structure.rst
Both the development of Bazaar and the project's URL `https://bazaar.canonical.com` have been discontinued.
Breezy is the community maintained continuation.
> Add current URL for Bazaar

- requirements.txt
- source/conf.py
- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
See https://github.com/pypa/packaging.python.org/pull/1251#issuecomment-1555881672 for context.
https://python-packaging-user-guide--1261.org.readthedocs.build/en/1261/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
> Add guidance for trusted publishing

- source/key_projects.rst
- source/specifications/core-metadata.rst
> Added obsolete fields: requires, provides and obsoletes

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
Fixes #1304.
As suggested, I chose adding an empty release body, but we could also demonstrate how to read from a changelog file.
Could I also include fixes for #777 and #804 to solve the issues in one piece?
> Add step to create empty GH Release before upload

- source/specifications/externally-managed-environments.rst
Addresses a small part of #1203 by adding a history section to the external management environments specification page.
> Add history section to externally managed environments spec.

- noxfile.py
- requirements.txt
I was having errors from the pinned version of `sphinx-autobuild`. 
- Updates to most recent release.
- Corrects CLI change in noxfile for autobuild host
> Update sphinx-autobuild version

- source/key_projects.rst
This adds binary backends scikit-build-core and maturin to the list of related packaging tools.
And changes:
* Multibuild now is in a org, the old link now is a fork.
* Distutils isn't part of the standard library anymore, so move it to a PyPI project and update the text.
> chore: add and update some backends

- source/guides/index.rst
This PR creates another section on the Guides index page. Move the two docs on hosting and indexes to the new section. This will keep the Installation section focused on users who are not self hosting.
> Add another category in guide index to put more advanced hosting/mirrors

- requirements.txt
- source/conf.py
- source/guides/distributing-packages-using-setuptools.rst
- source/overview.rst
- Upgrade to latest version of Sphinx (and other dependencies),
- Use "language = 'en'" in configuration since recent Sphinx versions do not accept "language = None" anymore,
- Add now required "%s" in extlinks config,
- Refer to setuptools explicitly in :std:doc: because Sphinx no longer implicitly uses intersphinx (by default) for this role. See https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_disabled_reftypes
The generated HTML can be compared using
$ diff -u build-old/ build-new | colordiff | diff-highlight
The only visible change is "Permalink to this headling" becoming "Link to this heading".
> Bump requirements

- source/flow.rst
- source/glossary.rst
- source/key_projects.rst
- source/specifications/declaring-project-metadata.rst
- source/specifications/source-distribution-format.rst
- source/tutorials/packaging-projects.rst
GitHub: fixes https://github.com/pypa/packaging.python.org/issues/1327
Preview:
* [Build Backend](https://python-packaging-user-guide--1329.org.readthedocs.build/en/1329/glossary/#term-Build-Backend)
* [Build Frontend](https://python-packaging-user-guide--1329.org.readthedocs.build/en/1329/glossary/#term-Build-Frontend)
> Add build backend and frontend to the glossary

- source/discussions/deploying-python-applications.rst
- source/discussions/install-requires-vs-requirements.rst
- source/guides/analyzing-pypi-package-downloads.rst
- source/guides/distributing-packages-using-setuptools.rst
- source/guides/index-mirrors-and-caches.rst
- source/guides/installing-scientific-packages.rst
- source/guides/installing-using-linux-tools.rst
- source/guides/packaging-binary-extensions.rst
- source/guides/supporting-multiple-python-versions.rst
- source/guides/supporting-windows-using-appveyor.rst
- source/overview.rst
- source/specifications/core-metadata.rst
- source/specifications/direct-url-data-structure.rst
- source/specifications/direct-url.rst
- source/tutorials/installing-packages.rst
They're not useful with Furo, which has a right sidebar with the local TOC, and they make it generate warnings in the rendered documentation.
@pradyunsg
> Remove contents directives

- source/conf.py
Follow up to @sinoroc's comment about the changed favicon: https://github.com/pypa/packaging.python.org/pull/791#issuecomment-1796411997
> Use a favicon instead of a logo

- noxfile.py
This enables incremental build with Sphinx.
Closes #1364 
Resolves #1363 by resolving the underlying concern.
https://gist.github.com/pradyunsg/27d99a7b08ea022fb28385b76c8d8e2b has the output, demonstrating the behaviour of this.
> Use a shared cache directory for Sphinx builds across nox sessions

- source/glossary.rst
- source/specifications/binary-distribution-format.rst
- source/specifications/core-metadata.rst
- source/specifications/declaring-project-metadata.rst
- source/specifications/dependency-specifiers.rst
- source/specifications/direct-url-data-structure.rst
- source/specifications/recording-installed-packages.rst
- source/specifications/version-specifiers.rst
- source/tutorials/installing-packages.rst
> Import PEP 440

- source/guides/index.rst
- source/guides/installing-using-virtualenv.rst
This PR is a follow up to #1338. In keeping with diaxtaxis doc process, this stub provides a starting point for a "how to" guide focused on using virtualenv to create isolated environments and installing packages. For now, it refers readers to the virtualenv documentation for details.
> Add stub for a how-to guide for virtualenv

- source/discussions/index.rst
- source/discussions/setup-py-deprecated.rst
PR preview demo: https://python-packaging-user-guide--1331.org.readthedocs.build/en/1331/discussions/setup-py-deprecated/.
> Add discussion "Is setup.py deprecated?"

- source/guides/index.rst
- source/guides/section-build-and-publish.rst
- source/guides/section-hosting.rst
- source/guides/section-install.rst
- source/index.rst
- source/overview.rst
This is largely aimed at making the sidebar less overwhelming when navigating to specific pages under guides, by grouping things via document hierarchy rather than multiple toctree entries in the same section.
(not needing this kind of stuff is a thing I want to support in Furo, but Sphinx doesn't expose that information in any way: https://github.com/sphinx-doc/sphinx/issues/10697)
> Improve sidebar presentation by tweaking titles and adding "section" pages for `guides/`

- .github/workflows/pr-preview-links.yml
This makes easier to review pull requests by providing the preview links in the PR description.
> Add a GitHub Action to inject preview links in PRs

- source/specifications/version-specifiers.rst
Follow on from https://github.com/pypa/packaging.python.org/pull/1340 which imported [PEP 440](https://peps.python.org/pep-0440/).
I left this "PEP" intact:
```rst
* Note: this comparison is to ``pkg_resourses.parse_version`` as it existed at
the time :pep:`440` was written. After the PEP was accepted, setuptools 6.0 and
later versions adopted the behaviour described here.
```
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1373.org.readthedocs.build/en/1373/
> Version specifiers: replace 'PEP' with 'specification'

- source/guides/installing-using-pip-and-virtual-environments.rst
This PR makes the following updates:
- remove all references to Python 2 and virtualenv and replace with a note at the top of the document
- change `env` environment name to `.venv` which is more commonly used and less likely to be confused with environment variables
- create 4 high level sections (pip, venv, install packages with pip, requirements files)
I view this PR as one of iteration of future iterations to improve individual documents in the guide.
> Update how to guide to install using pip and venv

- source/tutorials/packaging-projects.rst
This is a follow up on #1342: the tutorial implies that a Python package requires an `__init__.py` file.
I think that is the best to avoid this implication, otherwise we might "mis-educate" "packaging beginners" from the start.
The idea of this change is to introduce minimal rewording and a footnote.
The terms "regular package" and "namespace package" were introduced in [PEP 420](https://peps.python.org/pep-0420/), which is also very intentional when it comes to equating regular and namespace packages:
> A namespace package is not fundamentally different from a regular package. It is just a different way of creating packages. Once a namespace package is created, there is no functional difference between it and a regular package.
The change still recommends people that are getting started …
> Clarify that packages don't need `__init__.py`

- source/discussions/setup-py-deprecated.rst
- source/guides/modernize-setup-py-project.rst
- source/guides/section-build-and-publish.rst
- source/specifications/declaring-project-metadata.rst
This is meant as a starting point. There is much more to say, and that can be said in follow-up pull requests.
Preview (but there were some small modifications on other pages as well, mainly links):
* https://python-packaging-user-guide--1371.org.readthedocs.build/en/1371/guides/modernize-setup-py-project/
GitHub: refs https://github.com/pypa/packaging.python.org/issues/1334
> Add page "How to modernize a setup.py project?"

- source/specifications/externally-managed-environments.rst
This is similar to #1337 and #1340.
The first commit imports the PEP text as-is. All changes are done in the second commit so that reviewers can see what changed exactly. It is mostly trimming rationale/motivation sections and fixing markup for the PUG.
> Import PEP 668 specification

- .pre-commit-config.yaml
This PR fixes CI.
A new file in specifications has 2 german phrases. Add the words to the spelling ignore list.
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1386.org.readthedocs.build/en/1386/
> Add 2 german words to codespell to fix pre-commit check in CI

- source/news.rst
Partially addresses #1384 
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1387.org.readthedocs.build/en/1387/
> Add note that News doc is not currently being updated

- source/specifications/declaring-build-dependencies.rst
- source/specifications/index.rst
- source/specifications/inline-script-metadata.rst
This resembles https://github.com/pypa/packaging.python.org/pull/1372, https://github.com/pypa/packaging.python.org/pull/1340 and https://github.com/pypa/packaging.python.org/pull/1337.
Like those other PRs, it has one first commit importing the PEP text verbatim, and a second commit changing it. This is so that reviewers can see exactly what changed (content explaining the motivation and alternatives is trimmed, and some references are adjusted).
I'm fully aware that PEP 723 was only provisionally/conditionally accepted. I'd still like to have it in the PUG so that if/when it becomes accepted, all the announcements can read "Tool X now supports inline script metadata" instead of "Tool X now supports PEP 723". I guess it's clear by now that I don't like concepts referred to by PEP number …
> Import PEP 723 specification

- source/discussions/src-layout-vs-flat-layout.rst
- source/guides/packaging-namespace-packages.rst
This addresses the linked issues, and adds a `pyproject.toml` example for how to find native or implicit namespace packages with `setuptools`.
- Closes #1222
- Closes #689
- Closes #1305
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1379.org.readthedocs.build/en/1379/
> Improve namespace packaging guide

- source/guides/writing-pyproject-toml.rst
- source/tutorials/packaging-projects.rst
Replace links to the "Declaring project metadata" specification with links to the "Writing pyproject.toml guide" since this is more likely what the user wants after a tutorial. Also harmonize with the guide slightly and leave link to version specifier specification (advanced reading) for the guide.
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1391.org.readthedocs.build/en/1391/
> Link to pyproject.toml guide in "Packaging Python projects" tutorial

- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
Closes #777 
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1380.org.readthedocs.build/en/1380/
> Warn of exceeding PyPI project size limit in GHA guide

- source/key_projects.rst
Okay, I managed to figure out how to do this properly (I think). Maybe I'm the only one who feels this way, but sometimes GitHub is harder for me to understand than Git itself.
Anyway, here are a few quick changes to update the description of virtualenv and make it read more cleanly.
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1407.org.readthedocs.build/en/1407/
> Fix virtualenv description

- source/guides/modernize-setup-py-project.rst
Thank you for this guide, it's very useful!
Here's a few small proofreading suggestions.
* No need to italicise "pip"
* If we "**MUST NOT**" use the old commands, then upgrade "can be used" to "should be used" for the replacement commands
* Simplify "Current recommendation" -> "Recommendation". When it's no longer current, let's update it. (Same for the whole website.)
* Fix typo: `build-sytem` -> `build-system`
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1411.org.readthedocs.build/en/1411/
> Proofread 'How to modernize a setup.py based project?'

- source/key_projects.rst
https://packaging.python.org/en/latest/key_projects/#setuptools mentions the "distribute" fork under setuptools:
In 2023:
* the info about the "distribute" fork of setuptools is outdated - it was deprecated and merged back into setuptools in 2013: https://pypi.org/project/distribute/#history
* likewise, it's been a decade since setuptools 0.7 was released, supporting Python 2.4-2.7 and 3.1-3.3: https://pypi.org/project/setuptools/0.7.8/ Anyone using setuptools will have a much newer version.
* finally, setuptools is a fine choice but it's arguable that setuptools is no longer "the primary choice for Python packaging"
Let's remove this paragraph.
---
Also, the setuptools project normally capitalises the first letter when at the start of a sentence, or in a title. (And inconsistently uses …
> Remove outdated "distribute" fork info

- source/guides/installing-using-pip-and-virtual-environments.rst
I think this language is a little bit clearer, especially because it makes it clear that you aren't supposed to run the code block. The section could probably be made yet more clear, however.
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1413.org.readthedocs.build/en/1413/
> verbiage tweak in installing-using-pip-and-virtual-environments.rst

- .pre-commit-config.yaml
Closes #1403
~I'm not sure that I put the *.po file ignore in the correct place for the capitalization hook. If someone has a better solution, please update this PR. Thanks.~
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1404.org.readthedocs.build/en/1404/
> Ignore .po files for caps pre-commit hook

- source/discussions/setup-py-deprecated.rst
Add alternative solutions for more commands.
GitHub: relates to https://github.com/pypa/packaging.python.org/pull/1415
---
Direct link to added section in preview: https://python-packaging-user-guide--1418.org.readthedocs.build/en/1418/discussions/setup-py-deprecated/#what-about-other-commands
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1418.org.readthedocs.build/en/1418/
> Improve discussion "Is `setup.py` deprecated?"

- source/specifications/recording-installed-packages.rst
Distilled based on the conversation in https://github.com/pypa/pip/issues/11835#issuecomment-1833546937 and related comments (cc @pfmoore). Happy to modify language or whatever, or close if this recommendation is incorrect!
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1423.org.readthedocs.build/en/1423/
> DOC: Document RECORD modification

- source/conf.py
- source/tutorials/packaging-projects.rst
- Add links to advanced configuration for each build backend
- Replace link to "Packaging binary extensions" guide (an advanced topic, probably not what newcomers want to read) with links to the TOCs for guides and discussions
- Remove links to PEP 517 and PEP 518, which are technical standards, not user-facing documentation
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1432.org.readthedocs.build/en/1432/
> Improve "further reading" at end of "packaging projects" tutorial

- source/discussions/setup-py-deprecated.rst
GitHub: refs https://github.com/pypa/packaging.python.org/pull/1418
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1429.org.readthedocs.build/en/1429/
> Fix bits of "Is `setup.py` deprecated?" discussion

- source/conf.py
- source/guides/distributing-packages-using-setuptools.rst
- source/key_projects.rst
Fixes #1438
Also replace a few hyperlinks inside packaging.python.org with normal references.
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1439.org.readthedocs.build/en/1439/
> Remove the guide from its own Intersphinx mapping

- source/guides/installing-using-pip-and-virtual-environments.rst
I just watched a streamer on Twitch get stuck on this paragraph.
The docs said you should run `venv`, as if it's a command.
So that's what I'm attempting to address here.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1448.org.readthedocs.build/en/1448/
> Clarify docs for creating virtual environment

- source/guides/dropping-older-python-versions.rst
- source/guides/installing-using-linux-tools.rst
- source/guides/making-a-pypi-friendly-readme.rst
- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
- source/guides/using-testpypi.rst
- source/specifications/binary-distribution-format.rst
- source/specifications/core-metadata.rst
- source/specifications/dependency-specifiers.rst
- source/specifications/direct-url-data-structure.rst
- source/specifications/entry-points.rst
- source/specifications/recording-installed-packages.rst
- source/specifications/version-specifiers.rst
- source/tutorials/installing-packages.rst
- Fix reST syntax for definition lists in direct-url-data-structure.rst
- Wheel spec: Remove some remnants of the PEP format
- Wheel spec: Remove comparison to .egg, duplicated with source/guides/wheel-vs-egg.rst.
- Fix many spurious block quotes and wrong syntax highlighting languages
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1440.org.readthedocs.build/en/1440/
> Batched minor fixes

- source/guides/analyzing-pypi-package-downloads.rst
Fixing very minor typo: `it's` should be `its`
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1444.org.readthedocs.build/en/1444/
> Fix minor typo in analyzing-pypi-package-downloads.rst

- source/guides/distributing-packages-using-setuptools.rst
- source/guides/single-sourcing-package-version.rst
- source/guides/writing-pyproject-toml.rst
The [Packaging and Distributing Projects](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/) guide is quite outdated. It uses `setup.py` and no `pyproject.toml`. It's also out of sync with the sample project.
I'd like to update it, but this is going to be difficult to review if I do it in a single sweeping PR, so here's a start, to be continued later. This PR removes the descriptions of `setup()` arguments that have better equivalents in `[project]`. Where these descriptions had more details than the [Writing pyproject.toml](https://packaging.python.org/guides/writing-pyproject-toml/) guide, I have moved the details there.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1450.org.readthedocs.build/en/1450/
> Start updating distributing-packages-using-setuptools guide

- source/glossary.rst
The current link doesn't actually give the syntax of the requirement specifier. PEP 508 is much better.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1456.org.readthedocs.build/en/1456/
> glossary.rst: Update link to requirement specifier syntax to PEP 508

- source/guides/using-testpypi.rst
With the upcoming change to require 2FA for all users (already enforced on TestPyPI), update guidance to point the user in the right direction.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1457.org.readthedocs.build/en/1457/
> docs: update testpypi guide for api token

- source/guides/hosting-your-own-index.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1461.org.readthedocs.build/en/1461/
> Remove unnecessary word from documentation

- source/conf.py
We're getting frequent flaky CI failures due to the huge number of links that have to be checked, making the check sensitive to random connection errors.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1465.org.readthedocs.build/en/1465/
> Increase number of linkcheck retries

- .github/workflows/test-translations.yml
This workflow is intended for a centralized and easy to find point of syntax errors in translation files. 
Currently, one can only find syntax errors by browsing the logs in Read The Docs, and each language is its own separated rtd project. I doubt anyone will do that, except for me.
Translation file update triggers in both push and pull request events. E.g. When Weblate files a pull request with new translations.
Examples of runs:
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1431.org.readthedocs.build/en/1431/
> Test translations for reST syntax errors

- source/specifications/binary-distribution-format.rst
- source/specifications/core-metadata.rst
- source/specifications/dependency-specifiers.rst
- source/specifications/direct-url-data-structure.rst
- source/specifications/direct-url.rst
- source/specifications/entry-points.rst
- source/specifications/externally-managed-environments.rst
- source/specifications/inline-script-metadata.rst
- source/specifications/name-normalization.rst
- source/specifications/platform-compatibility-tags.rst
- source/specifications/pyproject-toml.rst
- source/specifications/recording-installed-packages.rst
- source/specifications/source-distribution-format.rst
- source/specifications/version-specifiers.rst
- source/specifications/virtual-environments.rst
Fixes #1203
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1464.org.readthedocs.build/en/1464/
> Consistent changelogs for all specs

- .github/workflows/test.yml
- .github/workflows/translation.yml
I'm getting notifications every day that workflow runs on my fork of this repository had failures.
- Test workflow: add condition to skip the daily run on forks in the `check` job, just like in the `build` job
- Translation workflow: likewise, skip on forks
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1436.org.readthedocs.build/en/1436/
> Prevent workflow failures on forks

- source/specifications/core-metadata.rst
- source/specifications/name-normalization.rst
- Rename the "Package name normalization" specification into "Package name grammar and normalization", to make it explicitly about the format of valid names too.
- Link to this spec in the core metadata specification instead of duplicating the part about valid names.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1463.org.readthedocs.build/en/1463/
> Deduplicate specification of valid package names

- source/specifications/platform-compatibility-tags.rst
Contains commits:
- Platform tags: Adjust to centralize history
Move history to a dedicated section (consistent with other specs). In
the main text, do not reference PEPs but just describe the current spec.
Also sketch out a few missing details.
- Remove note about manylinux_x_y being a new standard
It's been 4 years now.
- Platform tags: Flatten deeply nested headers
- Add musllinux platform tags from PEP 656 (relates to #1093)
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1441.org.readthedocs.build/en/1441/
> Revise platform tags spec, add musllinux

- .github/workflows/cron.yml
- .github/workflows/test.yml
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1475.org.readthedocs.build/en/1475/
> 🧪🔧 Move cron trigger to separate GHA workflow

- source/overview.rst
The list can be misconstrued as an endorsement and we can't keep up w/ all PaaS platforms which support Python to make the list comprehensive/impartial.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1479.org.readthedocs.build/en/1479/
> Remove the explicit list of PaaS platforms

- source/specifications/simple-repository-api.rst
A potential precursor to #1442, simply copying the specifications from the relevant PEPs and replacing PEP references with internal links. Specs are otherwise unchanged (eg dist-info-metadata field is not renamed in the original spec; this could be a future PR, or changed here if requested).
The spec history is also converted to a list to be consistent with other specs.
Solves part of #1093
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1477.org.readthedocs.build/en/1477/
> Migrate simple repository API specifications from PEPs

- source/key_projects.rst
Pex long ago stopped offering a programmatic API in favor of its CLI
API. I was remiss in not updating this description. Note is made of the
more expansive features Pex and PEX files have grown in the meantime,
including a nod to Pex multi-platform lock support (RIP PEP 665 - you
live on in Pex).
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1485.org.readthedocs.build/en/1485/
> Update pex entry.

- source/specifications/direct-url-data-structure.rst
- source/specifications/recording-installed-packages.rst
- source/specifications/simple-repository-api.rst
- source/specifications/version-specifiers.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1488.org.readthedocs.build/en/1488/
> Use intersphinx to link to `hashlib` docs

- source/specifications/dependency-specifiers.rst
- source/specifications/entry-points.rst
- source/specifications/name-normalization.rst
- source/specifications/platform-compatibility-tags.rst
- source/specifications/recording-installed-packages.rst
- source/specifications/virtual-environments.rst
Follow-on from https://github.com/pypa/packaging.python.org/pull/1488
See https://github.com/pypa/packaging.python.org/pull/1488#pullrequestreview-1843081477
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1489.org.readthedocs.build/en/1489/
> Use intersphinx to link to other Python docs

- .github/sphinx_lint_matcher.json
- .github/workflows/test-translations.yml
Changes in here include:
- Make sure that the lint is ran even when build fails
- Add problem matcher for both build and lint
- Update version of the action/setup-python action
Link of tests done: rffontenelle/packaging.python.org#3
Screenshot from my personal tests showing errors in a language:
Screenshot of the summary of a pull request:
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1469.org.readthedocs.build/en/1469/
> Add problem matcher for test-translations.yml

- source/specifications/core-metadata.rst
The current version disallows tripple hyphens but allows dubble hyphens. (It also seems overcomplicated)
Alternatively we can make it a negative lookbehind instead of a negative lookahead, but the complexity is much higher.
See https://regex101.com/r/Xyu0bt/1 for proof the current version matches double hyphens
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1491.org.readthedocs.build/en/1491/
> Replace regex which allows dubble hyphens by one that does not.

- source/guides/modernize-setup-py-project.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1497.org.readthedocs.build/en/1497/
> Fix a typo in the `pip install` command @ `modernize-setup-py-project.rst`

- source/conf.py
- source/guides/single-sourcing-package-version.rst
Related to failing queries to Stack overflow https://github.com/pypa/packaging.python.org/pull/1474
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1510.org.readthedocs.build/en/1510/
> Add stack overflow to linkcheck ignore list

- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
- source/guides/tool-recommendations.rst
- source/guides/writing-pyproject-toml.rst
This is my proposal to address #1468.
Fixes #1468
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1474.org.readthedocs.build/en/1474/guides/tool-recommendations/
> Update tool recommendations

- source/specifications/direct-url-data-structure.rst
Adds a JSON schema for the structure of `direct_url.json`.
Based on https://github.com/edgarrmondragon/pep610/blob/41a39253521637e85f364f60d1106c25dfa03d02/tests/fixtures/direct_url.schema.json with some changes to make it more accurate:
* Updated the JSON schema draft version to [2019-09](https://json-schema.org/draft/2019-09/release-notes) so `deprecated` can be used for `archive_info.hash`.
* Fixed the pattern of `archive_info.hash` to actually accomodate valid algorithm names. e.g. `md5=...` wouldn't have been valid before.
See the [discuss thread](https://discuss.python.org/t/clarify-that-the-direct-url-json-url-field-must-be-a-spec-compliant-url/46518/7) for more context.
Relevant docs preview: https://python-packaging-user-guide--1512.org.readthedocs.build/en/1512/specifications/dir …
> Document the JSON schema of `direct_url.json`

- source/guides/single-sourcing-package-version.rst
This file no longer exists on the `main` branch as of https://github.com/pypa/pip/pull/12537 /
https://github.com/pypa/pip/commit/0ad4c94b.
It's an alternative to removing the link performed in https://github.com/pypa/packaging.python.org/commit/3e65739d8078603eec17bc2a38a1bab1a74ccb37.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1514.org.readthedocs.build/en/1514/
> Point pip's `setup.py` link to its latest version

- source/specifications/direct-url-data-structure.rst
Clarify that the `url` field in `direct_url.json` must be a valid url. This was prompted by a case where the `url` field contained a value that was not a url (https://github.com/astral-sh/uv/issues/1744). I'm not sure what the best venue to discuss this change is, so i'm putting it up as a PR here.
Relatedly, would it make sense to write a json schem for direct_url.json? A machine readable spec would allow tooling to generate types and would simplify verification.
[Post on discuss.python.org](https://discuss.python.org/t/clarify-that-the-direct-url-json-url-field-must-be-a-spec-compliant-url/46518)
Closes #1510 (link check fix)
---
Thanks to whoever set up nox + sphinx-autobuild, `nox -s preview` is great!
---- …
> RFC: Clarify that the direct_url.json url field must be a spec-compliant url

- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
Adding a link to [GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions) on how to set up `GITHUB_TOKEN` permissions.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1518.org.readthedocs.build/en/1518/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#signing-the-distribution-packages
> Add a note on how to set up your `GITHUB_TOKEN` permissions to the publishing to PyPI from GHA guide

- source/guides/installing-stand-alone-command-line-tools.rst
The `cowsay` package now requires a `-t` argument.
I also noticed the output from pipx has changed a bit over time, so I updated the output to match the current format.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1520.org.readthedocs.build/en/1520/
> guides: stand-alone-tools: update in 2024

- source/tutorials/installing-packages.rst
As of Python 3.12, `python -m venv` does not install `setuptools` in the venv anymore (https://docs.python.org/3/library/venv.html#creating-virtual-environments).
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1530.org.readthedocs.build/en/1530/
> Update packages installed in venv

- source/specifications/pyproject-toml.rst
See https://github.com/pypa/pyproject-metadata/issues/30. This fills the Summary field, which must be a single line, so this should also be a single line. Historically, tools have done different things here. Setuptools removes anything after the first line. pyproject-metadata based backends (pdm-backend, scikit-build-core, and meson-python) join the lines into one line. The next version of scikit-build-core will error instead. Third party tools reading a config like this:
```toml
[project]
description = """Two
Line"""
```
Cannot know if the `Summary` will be `"Two Line"`, `"Two"`, or an error.
Enforcing this as one line also helps authors that put what should go into `project.readme.text` here instead.
There are three levels of response possible here, this PR is the middle one:
1. Just …
> pyproject.toml: specify description is one line

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
This bumps two referenced action versions:
1. The latest stable `setup-python` is `v5`, which is compatible with the previous use.
2. The example workflow previously referred to a very old version of `gh-action-sigstore-python`, which was no longer supported. This bumps it to a newer version that is similarly compatible with the previous use.
For (2), see https://github.com/sigstore/gh-action-sigstore-python/issues/122 for an example of a user who was snarled by the old version :slightly_smiling_face: 
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1539.org.readthedocs.build/en/1539/
> publish-to-test-pypi: bump action versions

- source/glossary.rst
The definitions were originally included in (the draft of) PEP 639, refining and extending the existing glossary terms.
Having the unified vocabulary in place is essential to accurately describe the complex Python packaging landscape.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1541.org.readthedocs.build/en/1541/glossary/#term-Built-Metadata
> Add glossary definitions of packaging and metadata terms

- source/tutorials/packaging-projects.rst
I thought the explanation of __init__.py was kind of confusing, so I have improved it somewhat.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1538.org.readthedocs.build/en/1538/
> Update packaging-projects.rst: rephrase first explanation of __init__.py

- source/conf.py
Metrics are only collected for the main packaging.python.org documentation deployments.
Closes #1561
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1564.org.readthedocs.build/en/1564/
> Add HTML snippet for Plausible metrics

- source/specifications/dependency-specifiers.rst
This PR makes a minor adjustment to the `version_many` grammar to allow a trailing comma to match the behavior of [`_parse_version_many`](https://github.com/pypa/packaging/blob/3e67fc775e93166600c84a5183ab6a86afff84b5/src/packaging/_parser.py#L220-L246).
Users may assume that setuptools `install_requires` is a comma separated list or otherwise leave trailing commas in dependency specifiers, leading to requirements like [`numpy >=1.19,`](https://inspector.pypi.io/project/pymixfit-tspspi/0.0.1/packages/23/a0/e3a6f5b3691cfc9c5aedf6f11cf9e806c40966a7250216a684ea62fdf90c/pymixfit_tspspi-0.0.1.tar.gz/pymixfit_tspspi-0.0.1/setup.cfg#line.21). Since https://github.com/pypa/packaging/pull/484 released in late 2022, the `packaging` package used by most packaging tools has been silently discarding …
> allow trailing comma in `version_many`

- source/discussions/src-layout-vs-flat-layout.rst
- source/guides/analyzing-pypi-package-downloads.rst
- source/guides/creating-command-line-tools.rst
- source/guides/installing-stand-alone-command-line-tools.rst
- source/guides/section-build-and-publish.rst
Part of #615. 
~~Declaring this blocked until a new version of `pipx` is released, as the part with the `pipx run` entry point won't work as expected right now.~~ Fixed in fresh-off-the-press `pipx` _1.6.0_. Review feedback is much welcomed, of course!
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1553.org.readthedocs.build/en/1553/
> Add guide on packaging command-line tooling

- source/specifications/direct-url-data-structure.rst
No changes to the spec, just adding a heading to
highlight the notes on avoiding credential leaks.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1585.org.readthedocs.build/en/1585/
> Add Direct URL security heading

- source/specifications/core-metadata.rst
So I ran into the issue over of the weekend of getting 502s from PyPI on upload of one of my repos. After exhausting everything else I found out that using the format for ``Provides-Dist`` in the spec causes uploads to fail because warehouse uses ``packaging.requirements.Requirement`` to validate wheel METADATA. See https://github.com/pypi/warehouse/issues/16452 It should also be noted that auditwheel and twine did not flag any problems with the wheel format and the only point of failure was a HTTP 502 from warehouse. It seemed in my judgement that editing the spec to keep people from running into this is a good idea. I defer to the PyPA team, though, it may be that warehouse needs changed instead as I am not privy to the original intent of the spec writers.
Thanks,
Eden Ross Duff
----
📚 …
> clarify ``Provides-Dist`` example to match warehouse metadata validation

- source/specifications/platform-compatibility-tags.rst
There's no arch tag.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1575.org.readthedocs.build/en/1575/
> Refer to platform tag as such in use example

- source/guides/creating-command-line-tools.rst
The import statement in `cli.py`, as written, fails. It doesn’t match the name of the file (`greet.py`) that is set up with the greet() function. 
An alternative solution would be to edit the name of `greet.py` to be `hello.py`, which I could also imagine being a useful approach, to avoid potential ambiguity from repeated words in different places. I chose to submit the simpler fix, though.
(By the way, thank you for this amazing guide! It’s so clear and helpful.)
One further thought/question: maybe it would be helpful to say that this can also be installed with pip? I wasn’t sure if I could just use pip and a venv, but didn’t want to add another layer of complexity to my setup, so I tried. And, sure enough, pip and a venv will install this, no problem! I get that you want to present a …
> Update creating-command-line-tools.rst to fix typo

- source/guides/writing-pyproject-toml.rst
Used clearer wording, instead of referring to tables as 'former' and 'latter', and some sentence cleanup.
I was reading the note and just noticed (ha) that it was a bit verbose. I removed some words and replaced them with direct mentions of the table names so it's easier to understand for first time readers.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1593.org.readthedocs.build/en/1593/
> Clarified note on [build-system] and [project]

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
Versions of actions/download-artifact before 4.1.7 are vulnerable to arbitrary file write when downloading and extracting a specifically crafted artifact that contains path traversal filenames.
Fore more details see: https://github.com/advisories/GHSA-6q32-hq47-5qq3
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1596.org.readthedocs.build/en/1596/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
> Update download-artifact plugin in publish-to-test-pypi.yml to fix vulnerability

- source/specifications/core-metadata.rst
- source/specifications/platform-compatibility-tags.rst
Starting to draft updates for PEP 693/Metadata 2.4.
~~I'm unsure how to capture the conflicts/deprecations.~~
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1595.org.readthedocs.build/en/1595/
> PEP 639: Add documentation for Metadata 2.4, License-Expression and License-Field

- source/discussions/setup-py-deprecated.rst
Lines 21 to 23 state that the `install` command must not be run anymore.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1572.org.readthedocs.build/en/1572/
> Fix conflicting classification of install

- source/contribute.rst
Update contribute.rst reference to out of date django documentation version
Point at dev dependency, which should always stay up to date
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1615.org.readthedocs.build/en/1615/
> Update contribute.rst reference to out of date django documentation version

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
closes #1610 
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1614.org.readthedocs.build/en/1614/
> upgrade gh-action-sigstore-python to v3.0.0

- source/specifications/version-specifiers.rst
This makes it possible to direct-link to this section from other Sphinx documentation, e.g. Python PEPs.
CC @miketheman 
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1625.org.readthedocs.build/en/1625/
> version-specifiers: add a custom anchor for `Pre-releases` section

- source/discussions/versioning.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1620.org.readthedocs.build/en/1620/
> PEP 396 was reclassifed as Withdrawn

- .pre-commit-config.yaml
Hi @webknjaz
I’ve addressed your feedback https://github.com/pypa/packaging.python.org/pull/1613#issuecomment-2445568431 in this PR.
Previously pre-commit.ci was seems run weekly, now I changed to quarterly. Let me know if you'd prefer to switch to a monthly schedule instead.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1629.org.readthedocs.build/en/1629/
> Change pre-commit.ci `autoupdate_schedule` to `quarterly`

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/general.yml
This is a follow up on a discussion on PyPA discord.
The hope is that having some mandatory fields will reduce the amount of spam or at least confuse a little bit the bots.
I am using the text `I am aware that participants in this repository must follow the PSF Code of Conduct`, instead of `I agree to follow the PSF Code of Conduct`, just to workaround some criticism we received in the past (e.g. https://discuss.python.org/t/what-to-do-with-contributors-who-refuse-code-of-conduct/13287).
Pretty much everything can be changed, this is just a initial draft to get things started.
I haven't been able to double check this renders correctly (so it may have problems). Possibly a maintainer also have access to Github UI to do this.
> Add simple issue template

- source/guides/analyzing-pypi-package-downloads.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1649.org.readthedocs.build/en/1649/
> Use syntax highlighting for BigQuery queries

- source/glossary.rst
Based on request from https://github.com/pypa/packaging.python.org/pull/1662#discussion_r1850418774
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1664.org.readthedocs.build/en/1664/
> Fix the alphabetic order of terms in Glossary

- source/tutorials/packaging-projects.rst
This PR updates the tutorial to match the expectations regarding api tokens from the latest version of twine.
See https://github.com/pypa/packaging-problems/issues/841
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1655.org.readthedocs.build/en/1655/
> Update packaging-projects.rst for entering API token

- source/conf.py
- source/specifications/index-hosted-attestations.rst
- source/specifications/section-package-indices.rst
- source/specifications/simple-repository-api.rst
Per https://github.com/python/peps/pull/4114: this imports the standard language parts of PEP 740, putting them in their appropriate living specs.
PEP 740 also stipulates changes to PyPI's upload API, which isn't currently standardized. Instead of inviting confusion there, I've removed that section of the PEP from the living spec and instead linked to Warehouse's upload API docs, which describe how attestations are uploaded on PyPI itself.
CC @di @dstufft 
----
* https://python-packaging-user-guide--1646.org.readthedocs.build/en/1646/specifications/index-hosted-attestations/
* https://python-packaging-user-guide--1646.org.readthedocs.build/en/1646/specifications/simple-repository-api/
> specifications: create living copy of PEP 740

- source/guides/tool-recommendations.rst
The docs currently say that only GitHub Actions is supported, but this is no longer true.
I've updated the section to include the currently supported providers, as well as include a rough date so that future readers can infer how old (and therefore stale) the list may be.
(I also added a `.. warning` callout to a statement that looked like it needed one. But I can undo that if desired!)
CC @webknjaz 
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1668.org.readthedocs.build/en/1668/
> tool-recommendations: update Trusted Publisher providers

- source/discussions/setup-py-deprecated.rst
I noticed it as it ended up in the translation strings.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1608.org.readthedocs.build/en/1608/
> Add a label to pganssle's post link on deprecating `setup.py`

- source/specifications/binary-distribution-format.rst
Following https://github.com/astral-sh/uv/issues/9656 and the discussion in the pypa discord (https://discord.com/channels/803025117553754132/837243676814999553/1314391181656064040), add a clarifying sentence that the scripts directory in wheels if for files only.
A future specification may want to extend this to "regular files and symlinks", for not it's limited to regular for clear rewrite semantics.
For ecosystem impact, uv errors when the scripts directory contains non-files and #9656 is the first time this error was reported.
CC @charliermarsh @pradyunsg @uranusjr 
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1673.org.readthedocs.build/en/1673/
> Clarify that the scripts directory is for files only

- requirements.txt
- source/conf.py
Makes it easier for people to contribute.
Before: 
After:
Needs Furo 2024.05.06. Docs: https://pradyunsg.me/furo/customisation/top-of-page-buttons/
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1670.org.readthedocs.build/en/1670/
> Theme: add view and edit buttons

- source/conf.py
Closes #1744
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1767.org.readthedocs.build/en/1767/
> Ignore PyPI anchors when checking links

- source/specifications/dependency-groups.rst
- source/specifications/section-distribution-metadata.rst
This is a first draft doc, based off of the original spec + reading the surrounding specs for examples of what's desirable.
I have in some cases reworded things from the original PEP document to try to simplify and clarify, but we can hew closer to the original spec text if that's preferable.
For example, I simplified the section which defines Dependency Group Includes: the spec defines `Dependency Object Specifiers`, the class of tables inside of dependency groups, and then defines one type of `Dependency Object Specifier`: a `Dependency Group Include`. I think that phrasing is good for the original PEP, which wants to lay out the idea that we could define other table types in the future, but not necessarily useful for someone who wants to just read and implement the spec as it currently …
> Add an initial specification doc for Dependency Groups

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
Closes #1748
Updates the "Signing the distribution packages" section to use environment variables rather than GitHub Actions context variables. No additional setting of environment variables are needed - these are all set/available already.
I've got a repo where we're using trusted publishing, although it's a slight variation on this, but hopefully it's an example that the environment variables work just fine:
https://github.com/developersociety/django-findreplace/blob/7fcf87397590b984dacaca58719f2d8b737d4f77/.github/workflows/publish.yml#L81
https://github.com/developersociety/django-findreplace/actions/runs/12457101550
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1765.org.readthedocs.build/en/1765/
> Use environment variables instead of contexts

- source/guides/installing-scientific-packages.rst
This page has changed significantly, linking to the entire page probably makes more sense instead now.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1773.org.readthedocs.build/en/1773/
> Fix link with missing anchor tag

- source/guides/writing-pyproject-toml.rst
There is a slight (but important) discrepancy between the docs and the actual behavior.
As observed here in this generated script:
```toml
[project.scripts]
build_autograder = "autograder_cli.build_autograder:tool"
```
```python
#!/usr/local/bin/python3
#-*- coding: utf-8 -*-
import re
import sys
from autograder_cli.build_autograder import tool
if __name__ == '__main__':
sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
sys.exit(tool())
```
We see that the return value from the tool is used as the exit code.
I had my code setup to return `True` in the case of a success and `False` in the case of a failure, thinking that the generated code would simply discard that return value.
As such, adding this one line will make it clear what the function should be returning.
----
📚 …
> Correct typo in docs for `[project.scripts]`

- source/specifications/source-distribution-format.rst
Specifically cover source trees and sdist as files.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1784.org.readthedocs.build/en/1784/
> Add labels to source-distribution-format.rst for cross-referencing

- source/glossary.rst
- source/guides/licensing-examples-and-user-scenarios.rst
- source/guides/section-build-and-publish.rst
- source/guides/writing-pyproject-toml.rst
- source/specifications/binary-distribution-format.rst
- source/specifications/pyproject-toml.rst
- source/specifications/recording-installed-packages.rst
- source/specifications/source-distribution-format.rst
- source/tutorials/packaging-projects.rst
Changed pages:
- glossary
- pyproject.toml
- sdist spec
- wheel spec
- installation spec
:question: The meaning of the `license` key in pyproject.toml is changed. The fact that table subkeys are deprecated is mentioned. Should I also keep the previous specification details?
:question: Cosmetic "unsureness": keep the changelog at November or antidate it to August when the PEP was provisionally accepted? Since the conditions of acceptance were just recently met, it's high time for these updates.
Resolves #1245.
----
* https://python-packaging-user-guide--1662.org.readthedocs.build/en/1662/glossary/#term-License-Classifier
* https://python-packaging-user-guide--1662.org.readthedocs.build/en/1662/guides/licensing-examples-and-user-scenarios/
* …
> Update the specification with PEP 639

- source/specifications/inline-script-metadata.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1777.org.readthedocs.build/en/1777/
> Minor fix to a missing in the inline script metadata doc.

- source/guides/writing-pyproject-toml.rst
Starting with [version 2.0 (Released Jan 5, 2025)](https://github.com/python-poetry/poetry/releases/tag/2.0.0) Poetry supports `[project]` table.
Fixes #1771
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1782.org.readthedocs.build/en/1782/
> Add a note that Poetry supports [project] now

- source/specifications/binary-distribution-format.rst
It's implied by https://packaging.python.org/en/latest/specifications/recording-installed-packages/#the-dist-info-directory as the resulting directory upon unpacking is supposed to be normalized.
----
* https://python-packaging-user-guide--1789.org.readthedocs.build/en/1789/specifications/binary-distribution-format/#file-contents
* https://python-packaging-user-guide--1789.org.readthedocs.build/en/1789/specifications/binary-distribution-format/#history
> Clearly specify that the name and version should be normalized for `.dist-info` and `.data` directories in wheels

- source/specifications/simple-repository-api.rst
See discussion in https://discuss.python.org/t/does-the-simple-repository-api-version-1-3-exist/79361 -- this updates the living index API spec to correctly reflect the latest API version (1.3), as well as add some callouts for the fields that make a response look like a 1.3 response (namely, provenance).
CC @di @brettcannon 
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1803.org.readthedocs.build/en/1803/
> simple-repository-api: bump, explain api-version

- source/specifications/simple-repository-api.rst
This follows #1803, and performs a few cleanup actions on the simple repository API docs:
- I've removed the `Additional Fields for the Simple API for Package Indexes` section entirely and have folded its prose into the relevant parts of the `JSON Serialization` section. This makes the doc as a whole easier to follow, since the user doesn't need to tab down to a different adjacent section to learn about the changes made with API version 1.1. It's also consistent with that was done with API version 1.3, i.e. PEP 740.
- I've added an `API Version History` subsection that lists only API versions and the PEPs that stabilized them. This should make it easier to cross-reference changes.
- I've moved the standard RFC 2119 language to the top of the document, since the entire doc uses it and not …
> simple-repository-api: clean up, add API history

- source/specifications/platform-compatibility-tags.rst
Adds documentation for the iOS PEP 730, Android PEP 738 platform tags. 
Also adds documentation for macOS tags, given they have their own quirks (especially regarding the ``universal`` fat architecture specification).
Fixes #1801 
Fixes #1802
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1804.org.readthedocs.build/en/1804/
> Document iOS, Android and macOS platform tag schemes.

- source/specifications/simple-repository-api.rst
This follows #1803 and #1808, as part of my effort to make the living index specification a bit easier to follow. Key changes:
1. I've removed the `Rename dist-info-metadata in the Simple API` section entirely, which seems to have come mostly verbatim from PEP 714. Instead, I've folded its prescriptions (renaming fields in both the HTML and JSON representations) into their relevant sections.
2. I've updated both the HTML and JSON sections to mention `data-core-metadata`/`core-metadata`, and have added admonitions noting that the old (PEP 658) names are considered legacy.
While doing the above, I noticed a minor errata (maybe even too small to be an errata?): PEP 658 and PEP 714 both change the Index APIs and happened after version 1.0 but *before* 1.1. Consequently, there was no version …
> simple-repository-api: clean up PEP 658/PEP 714 bits

- source/specifications/pyproject-toml.rst
Relates to #1813
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1814.org.readthedocs.build/en/1814/
> Fix the reference to License-File core metadata field

- source/guides/writing-pyproject-toml.rst
Add anchor links for `license` and `license-files` to make cross-linking from other projects easier.
In particular, I'd like to cross reference https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-files from the setuptools docs.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1816.org.readthedocs.build/en/1816/
> Add anchor links for license and license-files

- source/discussions/downstream-packaging.rst
- source/discussions/index.rst
A discussion aimed at explaining how downstream packaging works, what challenges are the packagers facing and how they can be helped.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1791.org.readthedocs.build/en/1791/
> A discussion on helping downstream packaging

- locales/ja/LC_MESSAGES/messages.po
Remove duplicated message, keeping the current one as available in Weblate.
Weblate has an [alert](https://hosted.weblate.org/projects/pypa/packaging-python-org/#alerts) saying that there are two equal messages in Japanese translation. See:
```
/home/weblate/data/vcs/pypa/packaging-python-org/locales/ja/LC_MESSAGES/messages.po:28729: duplicate message definition...
/home/weblate/data/vcs/pypa/packaging-python-org/locales/ja/LC_MESSAGES/messages.po:15112: ...this is the location of the first definition
msgmerge: found 1 fatal error
```
Looking at the translation file, I spotted the offending messages in line [15098](https://github.com/pypa/packaging.python.org/blob/cf3775cebb8f6973c372e7afe3fef02d7f03c6d0/locales/ja/LC_MESSAGES/messages.po#L15098) and in …
> Fix duplicate message in Japanese

- source/specifications/glob-patterns.rst
- source/specifications/pyproject-toml.rst
- source/specifications/section-distribution-metadata.rst
This is a follow up on the discussion in https://github.com/python/peps/issues/4299.
I basically extracted the existing text, but tried to make it slightly more generic so that it is not tied to `license-files` and can be reused somewhere else. Then I added a reference implementation based on @cdce8p's [contribution to Setuptools](https://github.com/pypa/setuptools/pull/4841).
It seems that other [PEPs in writing](https://discuss.python.org/t/pep-770-improving-measurability-of-python-packages-with-software-bill-of-materials/76308/68) are looking into using the same glob definition, so that would also be a good reason for the extraction.
Closes python/peps#4299
/cc @befeleme
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1826.org.readthedocs.build/en/1826/
> Extract glob specification to a separated document and add reference implementation

- source/glossary.rst
Just corrected a small typo in the glossary.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1671.org.readthedocs.build/en/1671/
> fix: typo in installed project glossary

- source/specifications/core-metadata.rst
- source/specifications/license-expression.rst
- source/specifications/pyproject-toml.rst
- source/specifications/section-distribution-metadata.rst
This brings the specification from PEP 639 body to packaging.python.org where it should be. 
yaml in the code block is to highlight the comments better in the rendered pages.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1838.org.readthedocs.build/en/1838/
> Specify SPDX license expression

- source/guides/licensing-examples-and-user-scenarios.rst
- source/guides/writing-pyproject-toml.rst
- source/shared/build-backend-tabs.rst
- source/tutorials/packaging-projects.rst
This updates the now outdated notes added in
faf4c7d882ef2be310d5dc46d54ca666aa18821c.
Closes #1831.
----
* https://python-packaging-user-guide--1837.org.readthedocs.build/en/1837/guides/writing-pyproject-toml/
* https://python-packaging-user-guide--1837.org.readthedocs.build/en/1837/guides/licensing-examples-and-user-scenarios/
* https://python-packaging-user-guide--1837.org.readthedocs.build/en/1837/tutorials/packaging-projects/
> Latest setuptools and flit now support PEP 639

- .github/CODEOWNERS
- requirements.txt
- source/conf.py
- source/specifications/build-details/examples/build-details-v1.0.json
- source/specifications/build-details/index.rst
- source/specifications/build-details/v1.0.rst
- source/specifications/index.rst
- source/specifications/schemas/build-details-v1.0.schema.json
- source/specifications/section-python-description-formats.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1807.org.readthedocs.build/en/1807/
> specifications: add build-details.json (PEP 739)

- source/conf.py
I'm evaluating the self-hosted option on the psf infrastructure.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1842.org.readthedocs.build/en/1842/
> Add psfhosted plausbile instance to analytics

- source/conf.py
we're going to be migrating to self-hosted plausbile entirely now.
drop plausible.io script, and enable outbound links
stats are now available at https://analytics.python.org/packaging.python.org/ instead of the old url of https://plausible.io/packaging.python.org
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1850.org.readthedocs.build/en/1850/
> remove plausible.io

- source/tutorials/installing-packages.rst
closes #1635
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1851.org.readthedocs.build/en/1851/
> docs: update installing-packages.rst

- source/specifications/binary-distribution-format.rst
- source/specifications/recording-installed-packages.rst
* Adds reservation of directory names under `.dist-info` and reserves a few names already in use.
* Adds description of `.dist-info/sboms` directory.
I wasn't sure whether to add a "guide" or not yet, as there aren't any especially "user-facing" ways to have an SBOM end up in this directory beyond your build backend/build tool supporting it. Should I leave that for a later task, then?
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1853.org.readthedocs.build/en/1853/
> Add PEP 770 to specifications

- source/conf.py
- source/specifications/dependency-specifiers.rst
- source/specifications/index.rst
- source/specifications/pylock-toml.rst
- source/specifications/pylock-toml/pylock.example.toml
- source/specifications/section-reproducible-environments.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1848.org.readthedocs.build/en/1848/
> Add PEP 751

- source/specifications/version-specifiers.rst
See https://discuss.python.org/t/are-developmental-releases-a-type-of-pre-release/81666/10 for approval of this change.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1857.org.readthedocs.build/en/1857/
> Clarify that dev releases are considered pre-releases when handling them

- source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
These steps are superfluous now that gh-action-pypi-publish generates and uploads PEP 740-compatible attestations by default on its own.
(They also served a slightly different purpose than PEP 740 attestations, since they were never uploaded to PyPI and used a different format.)
Closes #1788.
+CC @webknjaz @di for review 🙂
> guides: remove manual Sigstore steps from publishing guide

- source/guides/creating-command-line-tools.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1844.org.readthedocs.build/en/1844/
> grammar you->your

- source/specifications/dependency-groups.rst
This is a small example update based on some observed usage of Dependency Groups.
We wouldn't want to bloat the example, but many projects are using a `docs` group and this example therefore better exemplifies how Dependency Groups can be used to declare isolated/separate groups.
---
I argue for this change as net-good based on the fact that it shows that `docs` and `test` can be separate groups.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1860.org.readthedocs.build/en/1860/
> Add 'docs' to dependency groups example

- source/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.rst
- source/specifications/file-yanking.rst
- source/specifications/project-status-markers.rst
- source/specifications/section-package-indices.rst
- source/specifications/simple-repository-api.rst
This PR serves two purposes:
1. It integrates the recently-approved [PEP 792](https://peps.python.org/pep-0792/) into the living PyPUG specifications, so that I can complete the procedural step of linking to PyPUG from the PEP itself
2. In the process of integrating this spec into the living simple repository API spec, I attempted to clean up, streamline, and fix the "flow" of the current spec. In particular:
* I've moved the copy of the "yanking" PEP to its own page with proper linking, and made it consistent with how the other amending PEPs are documented (field changes are noted under the HTML and JSON sections with links to the separate page for full semantics)
* I've moved some of the more "mechanical" parts of the living spec (about normalized names, API versioning, etc.) to the top …
> simple-repository-api: add PEP 792, clean up layout

- source/conf.py
As the title says, this PR converts `linkcheck_ignore` entries to regexes so that the URLs really only match exactly (otherwise, a dot is interpreted as "any character").
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1883.org.readthedocs.build/en/1883/
> Convert linkcheck_ignore entries to regexes

- source/specifications/platform-compatibility-tags.rst
This will hopefully clarify/eliminate a contradiction in terms in the current specification text: the current text says both "sorted" and "set", where "set" conventionally implies an unordered collection.
In context that *appears* to have not been the intention, since the context is the wheel filename encoding and not the internal (i.e. parsed) representation
of a wheel filename's tags.
For context: this came up recently due to a set of unexpected tool interactions: 
* A user's build backend would produce a given wheel filename
* `auditwheel` would *rewrite* that wheel filename's tags, without enforcing a particular order
* `pypi-attestations` would "ultranormalize" the wheel's tags for signing and verifying purposes, to make string comparisons between wheel filenames work correctly. This …
> tags spec: clarify "sorted, set" to "sorted, collection"

- source/contribute.rst
The "Do not translate ..." part shoule be a definition list, not a blockquote, like the rest of this page.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1874.org.readthedocs.build/en/1874/
> Fix a small markup error in the contribute guide

- source/overview.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1912.org.readthedocs.build/en/1912/
> Vagrant link is failing CI, drop it entirely
