source/distributing.rst
a general section for wheel packaging, with three subsections for universal, pure, and platform
meant to handle #135
=> a general section for wheel packaging, with three subsections

source/single_source_version.rst
=> Don't hardcode path to package in example

source/distributing.rst
This should be a lot easier than filling the form by hand, which is what the text seems to suggest.
=> Recommend uploading PKG-INFO to register.

README.rst
=> Add the PyPA Code of Conduct

source/distributing.rst
I think `to` should not be there.
=> grammatical fix

source/install_requirements_linux.rst
Small addition for openSUSE (Python 2 & 3)
=> Add openSUSE section for pip/setuptools/wheel

source/install_requirements_linux.rst
Add the commands for installing pip on Arch Linux.
=> Add Arch Linux section for pip/setuptools/wheel

source/single_source_version.rst
Solutions based on version control systems.
=> Improve single_source_version.rst

source/current.rst, source/installing.rst, source/projects.rst
- update links to docs to reduce redirects
- closes #242
=> use venv instead of pyvenv

source/current.rst, source/key_projects.rst
- Added link to Spack.
- Fixed references to hashdist and conda.
=> Add Spack to the tool suggestions for scientific computing

source/conf.py
This will make casual bycomers more aware that this guide is up-to-date.
=> Update copyright year

source/plugin_discovery.rst
=> Add a note about namespace sub-packages to plugin discovery

source/distributing.rst
Based on and supersedes #273.
/cc @fboender
=> Mention requirement of 'wheel' package for creating wheels

source/namespace_packages.rst
=> Update links to namespace sample projects

.travis.yml
See: https://github.com/sphinx-doc/sphinx/issues/3754
=> Pin sphinx to 1.5.6 to unbreak CI

source/conf.py
Context: https://github.com/pypa/pypa-docs-theme/issues/3
=> Remove sidebar search to match Python docs

source/guides/migrating-to-pypi-org.rst
=> Wordsmith PyPI.org migration guide

nox.py
=> Make link checker warning-only

source/guides/migrating-to-pypi-org.rst, source/index.rst
=> Making new TestPyPI URL more visible, adding note to homepage about pypi.org

README.rst
=> Issue #207 README updated with how to build guide instructions

source/key_projects.rst
=> Add enscons to the list of key projects

source/key_projects.rst
=> Add flit to the key projects list

source/glossary.rst, source/guides/migrating-to-pypi-org.rst, source/index.rst, source/key_projects.rst
Resolves #363
/cc @mpeckWhisker
=> Add pypi.org term

source/tutorials/distributing-packages.rst
… in the Distributing Packages doc.
=> Fix a handful of typos, missing punctuation

source/new-tutorials/installing-and-using-packages.rst
=> Fix user base path instructions for Windows users

README.rst
A missing backtick and some grammatical improvements.
=> Fix some issues in the README

source/conf.py, source/index.rst, source/news.rst
=> Add News page

source/specifications/core-metadata.rst
=> Update section on Requires-Python

source/tutorials/distributing-packages.rst
Add note about README.rst getting included in sdists.
=> Explain README.rst in sdists

source/tutorials/distributing-packages.rst
=> Add a link to PyPI after the "Upload Your Distrubtions" step

source/guides/analyzing-pypi-package-downloads.rst, source/guides/index.rst
This guide points to the PyPI download statistics dataset and describes
how to query it.
Closes #428.
=> Provide pointer to Google BigQuery download statistics

source/guides/tool-recommendations.rst
=> Add pipenv to the Tool Recommendations guide

source/guides/tool-recommendations.rst
=> Update wheel footnote to mention manylinux

source/guides/installing-using-linux-tools.rst
=> Add python3-venv and python3-pip to Debian installation instructions

source/tutorials/distributing-packages.rst
Related to https://github.com/pypa/warehouse/issues/3229
=> Clarify long description classifier on pypi.org

source/discussions/install-requires-vs-requirements.rst, source/guides/creating-and-discovering-plugins.rst, source/guides/installing-using-pip-and-virtualenv.rst, source/guides/packaging-namespace-packages.rst, source/guides/single-sourcing-package-version.rst, source/guides/supporting-windows-using-appveyor.rst, source/key_projects.rst, source/news.rst, source/specifications/entry-points.rst, source/tutorials/distributing-packages.rst, source/tutorials/managing-dependencies.rst
Changes filenames written with code backticks to use the Sphinx [file directive](http://www.sphinx-doc.org/en/stable/markup/inline.html#role-file); ultimately, it renders the same.
This PR changes no *text*, only formatting.
=> Change ``filename`` to :file:`filename` throughout

source/guides/dropping-older-python-versions.rst, source/guides/installing-scientific-packages.rst, source/guides/multi-version-installs.rst
The other titles are in sentence case.
=> Title in sentence case for consistency

source/specifications/distribution-formats.rst
=> Update sdist specification to refer to PEP 517

source/tutorials/managing-dependencies.rst
=> Remove Easter egg from managing dependencies tutorial

source/tutorials/packaging-projects.rst
=> Expand the commands for uploading to the real PyPI in the packaging tutorial

source/tutorials/packaging-projects.rst
Fix minor typos in Packaging Projects tutorial.
=> Fix invalid url and small typo

source/guides/installing-using-pip-and-virtualenv.rst
=> Fix small typo

source/tutorials/packaging-projects.rst
Updated the nonexistent URL addressed in issue #529
=> Updating the nonexistent URL in example setup.py references 

source/tutorials/installing-packages.rst
since it is the only thing working in Windows cmd. And @ncoghlan said that this will also work in Linux. Resolving #548
=> Changed to double quotes in the pip install SomeProject==1.4

source/contribute.rst
Please see: https://github.com/theacodes/nox/commit/8cd1e6c93e628757b247559d3fac69ee2d572834
=> Update nox package name

source/guides/single-sourcing-package-version.rst
Hello,
I'm hoping this small change can be useful.
Thank you for the Guide!
Best regards,
Aliaksei
=> Make the warning about dependencies in __init__.py an actual warning admonition

source/tutorials/packaging-projects.rst
Hi, I'm giving some attention to the final paragraph of the packaging tutorial ... the "What to do next" section. I find the writing a bit complex, especially for tutorial-type content, as opposed to a reference document.
See what you think.
=> Grammar: active voice, remove a double negative

source/tutorials/packaging-projects.rst
=> Add username suffix to example package name in the packging tutorial

source/overview.rst
Add "according to" for the sentence to make more sense.
=> Improve sentence.

source/overview.rst
=> Fix duplicate word

source/key_projects.rst
Hi 👋 
Just as the subject states, just adding a blurb for `shiv` to the key projects section. Thanks for looking!
=> Add a blurb for shiv in the key projects section.

source/conf.py
Update copyright years.
Fixes #633.
=> Update copyright descriptions

source/guides/analyzing-pypi-package-downloads.rst
https://github.com/pypa/packaging.python.org/issues/638
=> Resolve Issue #638

source/guides/distributing-packages-using-setuptools.rst
=> Use `include` keyword in `find_packages()` call

source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
As per https://github.com/actions/setup-python/commit/6f6fcee33085a7661a7333ea58b4e32714b0f91f
=> Change deprecated version option to python-version

source/guides/packaging-binary-extensions.rst
Provide a simple CPython example of each of the three use cases mentioned in "Packaging binary extensions."
Additions highlighted:
This commit also bolds the 3 terms themselves to break up the long text block.
=> Binary extension use cases: provide examples

source/tutorials/installing-packages.rst
I saw that issue #393 was still open. If it still is open, would this be helpful?
Fixes #393.
=> Moved language around, adding how to activate a venv on Windows

source/guides/migrating-to-pypi-org.rst
Current docs show raw backticks.
=> add space to fix code markup

source/news.rst
Hello again! Take a look and let me know if you want anything added/removed.
=> Update news from Sep 2018 to Sep 2019

source/guides/index-mirrors-and-caches.rst
Updating an outdated link as referenced in #617
=> updating a broken link

source/tutorials/packaging-projects.rst
Added a comment and made the text uppercase to draw attention to it.
Fixes #652.
=> adding comment and making replace username bigger

source/guides/analyzing-pypi-package-downloads.rst
This PR makes the  'package downloads' guide a little more clear and up-to-date.
Fixes #632, fixes #664.
=> Revamp the 'package downloads' guide

source/guides/tool-recommendations.rst
Hi,
I think it's worth mentioning in the docs, that we have more tools available. As this is my first contribution here, any suggestions would be greatly appreciated. Just wanted to start with something.
Motivation - pipenv is not the only option out there and seems a bit abandoned:
https://github.com/pypa/pipenv/issues/4024
https://github.com/pypa/pipenv/issues/4058
=> Mention more tools in tool-recommendations.rst

source/tutorials/packaging-projects.rst
Include an empty test folder in the tutorial package layout.  Addresses Issue #619.
=> Add unit test folder

.github/CODEOWNERS
=> Mark myself as an owner for the GH Actions guide

source/specifications/simple-repository-api.rst
Followup to https://github.com/pypa/warehouse/pull/5838 . cc @ncoghlan .
Signed-off-by: Sumana Harihareswara <sh@changeset.nyc>
=> Add mention of PEP 592 for simple repo API spec

source/guides/distributing-packages-using-setuptools.rst
Fixes https://github.com/pypa/sampleproject/issues/117.
=> Remove link to sampleproject

source/key_projects.rst
Updated Dev List to "https://mail.python.org/mailman3/lists/distutils-sig.python.org/"
Fixes #732.
=> Updated key projects links per request

source/guides/distributing-packages-using-setuptools.rst
=> remove misleading comment

source/tutorials/creating-documentation.rst
Hi ;)
This command and text are incorrect, I made the correction.
=> Fix sphinx command and docs directory text

source/conf.py
Prepare for https://github.com/pypa/pypa-docs-theme/pull/19
=> Correctly use globaltoc.html for global ToC

source/key_projects.rst
Signed-off-by: Filipe Laíns <lains@riseup.net>
=> key_projects: add pypa/build

source/specifications/direct-url.rst, source/specifications/index.rst, source/specifications/recording-installed-packages.rst
As proposed by @ncoghlan in https://discuss.python.org/t/draft-pep-recording-the-origin-of-distributions-installed-from-direct-url-references/1535/41?u=sbidoul
=> Add reference to PEP 610

source/specifications/simple-repository-api.rst
=> Add PEP 629 to the Simple repository API spec page

source/guides/analyzing-pypi-package-downloads.rst
New location for dataset announced here: https://cloud.google.com/blog/products/open-source/supporting-the-python-ecosystem
=> update dataset to new Google-hosted location

source/guides/distributing-packages-using-setuptools.rst
This change combines #834 and #807 adding intersphinx refs on top.
=> Update setuptools link

source/conf.py, source/guides/distributing-packages-using-setuptools.rst
This change includes #728 adding interpshinx on top
=> Recommend twine check to check long description

source/tutorials/packaging-projects.rst
Discovered in https://github.com/pypa/packaging-problems/issues/458
=> fix: typos in setup.py

source/tutorials/packaging-projects.rst
Fix minor typos in the documentation.
=> Fixed typo

source/tutorials/installing-packages.rst
... when installing packages from PyPI.
=> docs: add info how to override pip's default behavior

noxfile.py, requirements.txt
=> Enable parallelism in Sphinx

source/tutorials/packaging-projects.rst
Closes #867. This provides some links for discovering more about MANIFEST.in and package data.
=> tutorial: add note about files

.readthedocs.yaml, requirements.txt, source/tutorials/packaging-projects.rst
Follow up to #818, see https://github.com/pypa/packaging.python.org/pull/818#issuecomment-817303874.
=> style: use file format in tab (newly supported)

.readthedocs.yaml
=> Configure ReadTheDocs to use the dirhtml builder

source/tutorials/packaging-projects.rst
The first of several (many?) small PR's towards #866. This one is mostly small additions/removals that didn't require restructuring the surrounding copy.
=> Packaging Python Projects: Small copy edits

source/tutorials/packaging-projects.rst
Towards #866. I shuffled some sentences around and removed some words to make this introduction flow a little better.
=> Packaging Python Projects: Restructure 'A simple project'

source/tutorials/packaging-projects.rst
=> Packaging Python Projects: Tweak README section

source/tutorials/packaging-projects.rst
=> Packaging Python Projects: Tweak API token instructions

source/key_projects.rst
@pypa/cibuildwheel-maintainers My description here is rather uninspired, feel free to expand and improve.
=> Add cibuildwheel to project list

source/tutorials/installing-packages.rst
=> Replace venv with virtualenv in example of installing-packages tutorial

source/guides/tool-recommendations.rst
=> Update the link to get-pip

source/tutorials/installing-packages.rst
=> Update `python` to `python3` in `installing-packages.rst`

.github/workflows/test.yml, .gitignore, locales/messages.pot, noxfile.py, requirements.txt, source/conf.py
- Refs #927 
- Generate `messages.pot` in `./locales` when running `nox -s translation` in the terminal
- Change the version of sphinx from `3.2.0` to `3.3.0`
#930 is too messy and I've closed it.
Thanks for review! :)
=> Generate `messages.pot` as translation template

source/conf.py, source/guides/tool-recommendations.rst
Builds on #896, will have an undefined label until that one goes in.
=> docs: update suggestion for build and cibuildwheel

requirements.txt, source/_static/overrides.css, source/conf.py
- This allows folks to copy commands directly with buttons.
=> Add Copy Button

source/guides/analyzing-pypi-package-downloads.rst, source/guides/index-mirrors-and-caches.rst, source/guides/installing-stand-alone-command-line-tools.rst, source/guides/using-testpypi.rst
=> Normalize command lines in code blocks

source/support.rst, source/tutorials/packaging-projects.rst
Followup to https://github.com/pypa/packaging-problems/pull/532 (should be merged after that one).
=> Use packaging-problems templates

source/tutorials/installing-packages.rst
=> Fix invalid command

source/overview.rst
=> remove bbFreeze link

source/conf.py, source/key_projects.rst
- See https://github.com/pypa/pipenv/issues/4805
@webknjaz
=> Use Wayback Machine for pipenv docs

source/conf.py, source/contribute.rst, source/guides/installing-scientific-packages.rst
While I was thinking about addressing #912, I decided to start with a smaller pull request first to get familiar with the contribution workflow and the expectations from reviewers.
This amends several build warnings I found because the SciPy website has changed a lot quite recently.
=> Fix some SciPy broken links

.gitignore, source/conf.py, source/tutorials/packaging-projects.rst
=> Update output filename in packaging-project

source/guides/using-manifest-in.rst
Seems like a weird place to have "&" instead of "and".
=> Tiny fixup to wording in MAINFEST.in guide

.github/workflows/test.yml
Follows https://github.com/pypa/setuptools/pull/3097
cc @di
=> Add concurrency limit to CI

source/specifications/binary-distribution-format.rst, source/specifications/core-metadata.rst
=> Fix spec for `Dynamic` to disallow `Metadata-Version`

source/key_projects.rst, source/specifications/pypirc.rst, source/tutorials/managing-dependencies.rst
v1 rewrite was just released https://discuss.python.org/t/hatch-1-0-0-is-available/15359
=> Update description of Hatch

source/key_projects.rst
Matches the other projects now
=> Add docs link to Hatch section

source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml
=> Use the release-branch in GHA publish snippets

source/tutorials/packaging-projects.rst
Twine switched to Rich for its progress bars awhile back.
=> Update Twine output

source/guides/distributing-packages-using-setuptools.rst
Related to #792 -- there's some more direct links but i couldn't find the intersphinx references [here](https://webknjaz.github.io/intersphinx-untangled/setuptools.rtfd.io/)
=> replaced direct link with intersphinx reference

source/guides/packaging-binary-extensions.rst
=> Don't highlight TODO lists as code

.github/workflows/test.yml
Hopefully this enables us to respond to `linkcheck` failures more quickly.
=> Run test workflow daily

source/key_projects.rst
Signed-off-by: Filipe Laíns <lains@riseup.net>
=> key_projects: add meson-python

source/specifications/declaring-project-metadata.rst
Closes https://github.com/pypa/packaging.python.org/issues/895
This also avoids confusion for people who don't know that Pradyun and Tzu-Ping are different humans. :)
=> Improve the pyproject.toml `project` table specification page

source/guides/creating-and-discovering-plugins.rst
=> Fixed typo on 'Creating and discovering plugins' page

source/overview.rst
Not necessarily typos, so if you'd like for me to update the commit I'd be happy to.
=> Fix typos in overview

source/conf.py, source/overview.rst
Looks like this has been fixed faster than expected. Reverts part of #1247
=> Homepage of bottlepy is running again

source/guides/dropping-older-python-versions.rst, source/guides/installing-using-linux-tools.rst, source/guides/installing-using-pip-and-virtual-environments.rst
This are some low-level improvements for readability.
=> Improve heading and remove space in commands

source/discussions/install-requires-vs-requirements.rst
GitHub: fixes https://github.com/pypa/packaging.python.org/issues/1223
=> Remove reference to SemVer to justify upper bound

source/specifications/dependency-specifiers.rst
Saw this low hanging fruit hanging around - let me know if you were looking for something more elaborate!
Closes #1194
=> Update extras example to use unioned dependencies

source/guides/analyzing-pypi-package-downloads.rst, source/guides/distributing-packages-using-setuptools.rst, source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml, source/guides/index-mirrors-and-caches.rst, source/guides/multi-version-installs.rst
I fixed some mistakes found while reading the guide.
=> Replace `python` interpreter with `python3`

source/discussions/wheel-vs-egg.rst
Refs: https://peps.python.org/pep-0715/
=> docs: add notice about PEP 715

.github/workflows/test.yml, source/contribute.rst
Updated in different places at different times.
Make consistent for now.
Refs: https://github.com/pypa/packaging.python.org/pull/820/commits/675acbb5eb3f9ebfa954bf603ecdc3d24b202533
Refs: https://github.com/pypa/packaging.python.org/pull/1247/commits/90a1d075646846a3a56dbbc0164ec7efaf729d5b
=> chore: update python versions used

source/index.rst
This PR is focused on the end user of the documentation. It edits the landing page to more closely reflect the diataxis structure of the documentation. The intent of the PR is to improve the experience of readers and help guide them to information that will be most valuable for their use case.
=> Rework the landing page to reflect diataxis principles

source/specifications/name-normalization.rst, source/tutorials/installing-packages.rst
xref: https://github.com/sphinx-contrib/sphinx-lint/issues/98
=> Use correct reST syntax for emphasis

source/tutorials/packaging-projects.rst
GitHub: fixes https://github.com/pypa/packaging.python.org/issues/1292
=> Clarify sentence about empty __init__.py

source/key_projects.rst
As suggested by @pradyunsg on the mailing list. 
It would be good to know who for the other projects.
=> Say that flit is lifted and by whom

noxfile.py
=> Allow Sphinx to do incremental builds

source/guides/installing-using-pip-and-virtual-environments.rst
Fixes #1375
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1378.org.readthedocs.build/en/1378/
=> Consistent tabs in installing-using-pip-and-virtual-environments.rst

source/guides/writing-pyproject-toml.rst, source/tutorials/packaging-projects.rst
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1392.org.readthedocs.build/en/1392/
=> Expand pyproject.toml guide to also cover the [build-system] table

.pre-commit-config.yaml
Closes #1389 
----
:books: Documentation preview :books:: https://python-packaging-user-guide--1400.org.readthedocs.build/en/1400/
=> Exclude precommit codespell check for translation po files

source/specifications/version-specifiers.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1451.org.readthedocs.build/en/1451/
=> Typo fix (closes #1416)

source/discussions/setup-py-deprecated.rst
`noxfile.py` since
https://github.com/wntrblm/nox/releases/tag/2018.8.23
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1453.org.readthedocs.build/en/1453/
=> Update nox config filename

source/guides/installing-using-pip-and-virtual-environments.rst
Fixes #1459
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1460.org.readthedocs.build/en/1460/
=> Correct path to venv scripts on Windows

source/specifications/direct-url-data-structure.rst
Context: https://github.com/astral-sh/uv/issues/3014
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1531.org.readthedocs.build/en/1531/
=> Update language for the direct URL data structure

source/specifications/inline-script-metadata.rst
https://github.com/python/peps/pull/3772
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1544.org.readthedocs.build/en/1544/
=> Add reference for inline script metadata spec

source/specifications/binary-distribution-format.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1551.org.readthedocs.build/en/1551/
=> binary-distribution-format: Update a mention of distutils

source/specifications/direct-url-data-structure.rst, source/specifications/externally-managed-environments.rst, source/specifications/simple-repository-api.rst, source/specifications/version-specifiers.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1576.org.readthedocs.build/en/1576/
=> Spelling and grammar fixes

source/specifications/dependency-specifiers.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1780.org.readthedocs.build/en/1780/
=> Add labels to dependency-specifiers.rst for cross-referencing

source/specifications/direct-url-data-structure.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1785.org.readthedocs.build/en/1785/
=> Add labels to direct-url-data-structure.rst for cross-referencing

source/specifications/core-metadata.rst
Per https://github.com/pypa/setuptools/issues/4797#issuecomment-2589514950, cc @pfmoore.
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1787.org.readthedocs.build/en/1787/
=> Add definition of deprecated metadata fields

source/tutorials/packaging-projects.rst
Closes https://github.com/pypa/packaging.python.org/issues/1845
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1846.org.readthedocs.build/en/1846/
=> Update packaging-projects.rst: set requires-python to 3.9

source/discussions/setup-py-deprecated.rst
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1890.org.readthedocs.build/en/1890/
=> Fix broken setuptools-scm link

source/guides/creating-command-line-tools.rst
Closes #1907
----
📚 Documentation preview 📚: https://python-packaging-user-guide--1913.org.readthedocs.build/en/1913/
=> Avoid binary gender assumptions in example
